In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv("../out/csvfile/unknown/unknown_1-200_ver1.csv")

FileNotFoundError: [Errno 2] No such file or directory: '../out/csvfile/unknown/unknown_1-200_ver1.csv'

In [20]:
df = df.sort_values(by="sigma", ascending=False, ignore_index=True)
for i in range(len(df)):
    print(df.loc[i, "smiles"], df.loc[i, "sigma"])

O=C(O)C1=C(C(=O)O)C(=CC=C1N(=O)=O)N(=O)=O 2.930214292816916
O=C(O)C=1C=C(C(=CC1C(=O)O)N(=O)=O)N(=O)=O 2.768663570936261
O=C(O)C1=C(O)C=C2C(=O)C=3C(O)=C(C(C(=O)C)=C(O)C3C(=O)C2=C1C(=O)O)CC 2.747609202775129
O=C(O)C1=CC=C(C(=C1C(=O)O)N(=O)=O)N(=O)=O 2.6599462859400376
O=C(O)C1=C(O)C=C2C(=O)C3=C(O)C(O)=C(C(O)=C3C(=O)C2=C1C(=O)O)C4=CC(=CC=C4O)CCN 2.5157570700488705
N#CC=1C=C(C(=O)O)C(=CC1C#N)C(=O)O 2.4919986473785443
O=C(O)C1=CC=C(C(NC(=O)C)=C1C(=O)O)N(=O)=O 2.454859356868141
O=C(O)C1=C(F)C(F)=C(O)C(F)=C1C(=O)O 2.4427838527918952
O=C(O)C=1C(Br)=CC=C(Br)C1C(=O)O 2.4418220834610778
O=C(O)C=1C(Cl)=CC=C(Cl)C1C(=O)O 2.437991329457852
O=C(O)C1=C(C(=O)O)C(=CC=C1C)C 2.4275593084400304
O=C(O)C=1C(F)=CC=C(F)C1C(=O)O 2.404307450353221
O=C(O)C=1C=C(C=C(C(=O)O)C1C(=O)O)N(=O)=O 2.402422281885402
O=C(O)C=1C(Cl)=CC(Cl)=C(Cl)C1C(=O)O 2.375176253843068
O=C(O)C=1C(OC)=CC=C(OC)C1C(=O)O 2.3652091178558603
O=C(O)C=1C(F)=CC=C(Br)C1C(=O)O 2.359820433005323
O=C(O)C=1C(Cl)=CC=C(C1C(=O)O)C(F)(F)F 2.3578149786040843
O=C(O)C=1C=C(C(=O)O)C(C(=O)O)=C(C(=O)O)C1C(=O)O 2.3288037898554834
O=C(O)C=1C(Br)=C(Br)C(Br)=C(Br)C1C(=O)O 2.318519532246466
O=C(O)C=1C=C(C(=O)O)C(=CC1C(=O)O)S(=O)(=O)O 2.315774251821954
O=C(O)C1=C(OCC)C=2C=CC=CC2C(OCC)=C1C(=O)O 2.3131215370289566
O=C(O)C1=CC(Cl)=C(C(=O)O)C(C(=O)O)=C1Cl 2.3071376565581176
O=C(O)C1=CC=C(C=C1C(=O)O)S(=O)(=O)N 2.3070252319393045
O=C(O)C=1C(F)=CC=C(C1C(=O)O)C 2.305027269826762
O=C(O)C=1C(C(=O)O)=C(C(C(=O)O)=C(C(=O)O)C1C(F)(F)F)C(F)(F)F 2.296707393240039
O=C(O)C=1C(O)=CC=C(O)C1C(=O)O 2.2948514858164595
O=C(O)C=1C(Cl)=C(Cl)C(Cl)=C(Cl)C1C(=O)O 2.294372787526013
O=C(O)C1=CC(N)=C(C=C1C(=O)O)N(=O)=O 2.288049816840044
O=C(O)C1=CC=C(C=C1C(=O)O)S(=O)(=O)C2=CC=C(C(=O)O)C(=C2)C(=O)O 2.2778325803330435
O=C(O)C=1C(Br)=C(C(=O)O)C(C(=O)O)=C(Br)C1C(=O)O 2.268523398207706
O=C(O)C=1C=C(C=C(C1C(=O)O)N(=O)=O)N(=O)=O 2.23345590155573
O=C(O)C1=CC(N)=CC(C(=O)O)=C1C(=O)O 2.1825684933055047
O=NC1=CC=CC(C(=O)O)=C1C(=O)O 2.17483198984715
O=C(O)C=1C=C(C(=O)O)C(=CC1N)C(=O)O 2.164407816011233
O=C(O)C=1C=C(C(=O)O)C(=CC1C(=O)O)N(=O)=O 2.1612387723066986
O=C(O)C1=CC=C(C=C1C(=O)O)N(=O)=O 2.1455507500977182
O=C(O)C1=CC=C(C=C1C(=O)O)NN 2.13804649820483
O=C(O)C1=CC=C(F)C(=C1C(=O)O)N(=O)=O 2.1094742904299237
O=C(O)C1=CC=C(Cl)C(=C1C(=O)O)N(=O)=O 2.107684134308401
O=C(O)C1=CC(N=NC=2C=C(C(=O)O)C(C(=O)O)=C(C2)C(=O)O)=CC(C(=O)O)=C1C(=O)O 2.105694675305722
O=C(O)C1=CC=C(C=C1C(=O)O)S(=O)(=O)O 2.1036300907218384
O=C(O)C1=CC=C(OC2=CC=C(C=C2)N(=O)=O)C=C1C(=O)O 2.0912433895920635
O=C(O)C1=CC=CC(=C1C(=O)O)N(=O)=O 2.090863474530249
O=C(O)C1=CC=C(OC)C(OC)=C1C(=O)O 2.088446944789562
O=C(O)C=1C=CC=C(OCC2=CC=C(C=C2)CO)C1C(=O)O 2.0826334554976595
O=C(O)C=1C=C(C(=O)O)C(C(=O)O)=C(C1C(=O)O)C(F)(F)F 2.071496365032008
O=C(O)C=1C=CC=C(OC2=CC=C(C=C2)C)C1C(=O)O 2.053345025760734
O=C(O)C1=CC=C(C=C1C(=O)O)C(=O)C2=CC=C(C=C2)C(=O)C3=CC=C(C(=O)O)C(=C3)C(=O)O 2.040004854764402
O=C(O)C=1C=CC=C(N=N(=O)C=2C=CC=C(C(=O)O)C2C(=O)O)C1C(=O)O 2.0341693672373697
O=C(O)C=1C=C(C(=O)O)C(=CC1C(=O)O)C(=O)C=2C=CC=CC2 2.0334467567894494
O=C(O)C=1C=CC=C(C=C)C1C(=O)O 2.0270686055598173
O=C(O)C1=CC=2N=CNC2C=C1C(=O)O 2.026339179472981
O=C(O)C1=CC=C(C=C1)C=2C=CC=C(C(=O)O)C2C(=O)O 2.025746740363001
O=C(O)C=1C=C(F)C=C(F)C1C(=O)O 2.0250410522104785
O=C(O)C1=CC=CC(C=2C=CC=CC2C)=C1C(=O)O 2.0218097197620124
O=C(O)C1=CC=C(O)C(O)=C1C(=O)O 2.0194820865912844
O=C(O)C1=CC(Br)=CC(F)=C1C(=O)O 2.0176333240401108
O=C(O)C1=CC=CC(C=2C=CC=CC2)=C1C(=O)O 2.016257616577702
O=C(O)C1=CC=C(N=NC2=CC=C(C(=O)O)C(=C2)C(=O)O)C=C1C(=O)O 2.0147307495996056
O=C(O)C=1C=C(C=C(C1C(=O)O)C)C 2.012905974665652
O=C(O)C1=CC(OC)=CC(=C1C(=O)O)C 2.0126244179782224
O=C(O)C1=CC(O)=C(C(=O)O)C(=C1)C(=O)O 2.0122924556013357
O=C(O)C=1C=CC=C(F)C1C(=O)O 2.0121657868585414
O=C(O)C1=CC(OC)=C(OC)C=C1C(=O)O 2.0093673170097563
O=C(O)C1=CC=CC(=C1C(=O)O)C 2.007654608351532
O=C(O)C=1C=CC=C(NO)C1C(=O)O 2.007559199898353
O=C(O)C1=CC=C(C=C1C(=O)O)NC(=O)C 2.006458602426278
O=C(O)C=1C=CC=C(Cl)C1C(=O)O 2.0037490804261218
O=C(O)C=1C=CC=C(Br)C1C(=O)O 2.003520089835304
O=C(O)C1=CC=C2C(=C1C(=O)O)C(C=3C=CC=CC3)(C)CC2(C)C 2.0033256718020938
O=C(O)C1=CC(OC)=C(OC)C(OC)=C1C(=O)O 2.001873088072952
O=C(O)C1=CC(Br)=CC(Cl)=C1C(=O)O 1.9979218168983863
O=C(O)C=1C=CC=C(NCC=2SC=CC2)C1C(=O)O 1.996460553796137
O=C(O)C=1C=C(Cl)C=C(Cl)C1C(=O)O 1.9942672032460689
O=C(O)C1=CC=C(C#C)C=C1C(=O)O 1.9936371643269195
O=C(O)C1=CC=CC(C(=O)O)=C1C(=O)O 1.9917263373636067
O=C(O)C1=CC=C(Cl)C(Cl)=C1C(=O)O 1.989581283640968
O=C(O)C=1C=CC=C(NCC=2C=NC=CC2)C1C(=O)O 1.9891655498734493
O=C(O)C1=CC=C(C(N)=C1C(=O)O)C 1.989014760933636
O=C(O)C1=CC(O)=CC(C(=O)O)=C1C(=O)O 1.9878812368522387
O=C(O)C1=CC=C(Br)C(F)=C1C(=O)O 1.987714556444571
O=C(O)C1=CC=C(F)C(F)=C1C(=O)O 1.9875573226835128
O=C(O)C=1C=CC=C(N)C1C(=O)O 1.986737094402596
O=C(O)C=1C=CC=C(NCC)C1C(=O)O 1.9864340440514
O=C(O)C=1C=C(OC)C=C(OC)C1C(=O)O 1.986134056568422
O=C(O)C=1C=CC=C(OC)C1C(=O)O 1.9840450232557647
O=C(O)C1=CC=CC(=C1C(=O)O)S(=O)(=O)N 1.983865396831393
O=C(O)C1=CC=C(C(OC)=C1C(=O)O)C 1.9827948588585744
O=C(O)C=1C=CC=C(NCC2CC2)C1C(=O)O 1.9820791675135288
O=C(O)C=1C=CC=C(NN)C1C(=O)O 1.982056419795716
O=C(O)C1=CC=C(F)C(Br)=C1C(=O)O 1.981918934646664
O=C(O)C1=CC=2C=CNC2C=C1C(=O)O 1.9813374444916163
O=C(O)C1=CC=C(OS(=O)(=O)C=2C=CC=CC2)C=C1C(=O)O 1.981151493939164
O=C(O)C=1C=CC=C(NC(=O)OCC2C=3C=CC=CC3C=4C=CC=CC42)C1C(=O)O 1.980367612047994
O=C(O)C=1C=CC=C(NCC=2OC(=CC2)C)C1C(=O)O 1.9802812930881328
O=C(O)C1=CC=C(C(=O)O)C(C(=O)O)=C1C(=O)O 1.9794769100944436
O=C(O)C=1C=CC=C(O)C1C(=O)O 1.9786501811082395
O=C(O)C1=CC(F)=CC(=C1C(=O)O)C 1.9771321512352504
O=C(O)C1=CC=C(OC2=CC=CC(OC3=CC=C(C(=O)O)C(=C3)C(=O)O)=C2)C=C1C(=O)O 1.976869969283081
O=C(O)C=1C=CC=C(NC(=O)OC(C)(C)C)C1C(=O)O 1.9767999511562933
O=C(O)C1=CC=C(OC2=CC=CC(C(=O)O)=C2C(=O)O)C=C1 1.9745826344146469
O=C(Cl)C1=CC=C(C(=O)O)C(=C1)C(=O)O 1.97156506767071
O=C(O)C1=CC=C2N=CC=CC2=C1C(=O)O 1.9711702196819991
O=C(O)C=1C=C(C(=O)O)C(C(=O)O)=C(C1)C(=O)O 1.9704670888019709
O=C(O)C1=CC=C(C=C1C(=O)O)N2C(=O)C=CC2=O 1.969594278344444
O=C(O)C=1C=CC=2C=CC=CC2C1C(=O)O 1.969447915090656
O=C(O)C1=CC(O)=C(C(=O)O)C(=C1C(=O)O)C 1.9671496070800611
O=C(O)C1=CC=C(F)C(=C1C(=O)O)C(F)(F)F 1.9665232626724984
O=C(O)C=1C=CC=C(OC2=CC=CC(C(=O)O)=C2C(=O)O)C1 1.9660249613822396
O=C(O)C1=CC(Cl)=C(Cl)C(Cl)=C1C(=O)O 1.9658791130132771
N#CC1=CC=C(C(=O)O)C(=C1)C(=O)O 1.9619360475499328
O=C(O)C1=CC(OC)=C(Cl)C(Cl)=C1C(=O)O 1.9617842622621893
O=C(O)C1=CC=C(C=C1C(=O)O)NC(=O)OC(C)(C)C 1.9617687353361648
O=C(O)C=1C=C2C=C3C=C(C(=O)O)C(=CC3=CC2=CC1C(=O)O)C(=O)O 1.9598942518056488
O=C(O)C1=CC(O)=C(N)C=C1C(=O)O 1.9570722992608856
O=C(O)C1=CC=C(F)C=C1C(=O)O 1.9549434691810537
O=C(O)C1=CC=C(OC2=CC=C(N)C=C2)C=C1C(=O)O 1.951328308255276
O=C(O)C=1C=CC=CC1C(=O)O 1.9508984582651625
O=C(O)C1=CC=C(C=C1C(=O)O)C(NC(=O)OC(C=2C=CC=CC2N(=O)=O)C)C(=O)O 1.949274031141408
O=CC1=CC=C(C(=O)O)C(=C1)C(=O)O 1.94886831118798
O=C(O)C1=CC=C(OC2=CC=C(C(=O)O)C(=C2)C(=O)O)C=C1C(=O)O 1.9476034912742763
O=C(O)C1=CC=C(C=C1C(=O)O)C(=O)C2=CC=C(C(=O)O)C(=C2)C(=O)O 1.9438140075436592
O=C(O)C1=CC(N)=C(N)C=C1C(=O)O 1.9426462290207176
O=C(O)C1=CC=C(Cl)C=C1C(=O)O 1.9401596914547337
O=C(O)C1=CC=C(Br)C=C1C(=O)O 1.9400272416075923
O=C(O)C=1C=C(C(=O)O)C(=CC1C(=O)O)C(=O)O 1.9345426116256452
O=C(O)C1=CC=C(C=C)C=C1C(=O)O 1.93157134286519
O=C(O)C1=CC=C(C=C1C(=O)O)C(=O)C=2C=CC=CC2 1.9313932683474784
O=C(O)C1=CC=C(C(=O)O)C(=C1)C(=O)O 1.9295282104567733
O=C(O)C=1C=CC(=CC1)C2=CC(C(=O)O)=C(C=C2C3=CC=C(C=C3)C(=O)O)C(=O)O 1.9288334630978283
O=C(O)C1=CC=C(C=C1C(=O)O)C(C2=CC=C(C(=O)O)C(=C2)C(=O)O)(C(F)(F)F)C(F)(F)F 1.9281676321169676
O=C(O)C1=CC=C(C#CC=2C=CC=CC2)C=C1C(=O)O 1.9274005530095284
O=C(O)C1=CC=C(S)C=C1C(=O)O 1.927182486265094
O=C(O)C1=CC=C(C=C1C(=O)O)C(=O)OCCOC(=O)C(=C)C 1.925400127012876
O=C(O)C1=CC=C(OC(C)C)C=C1C(=O)O 1.921032980658812
O=C(O)C1=CC=C(OCC)C=C1C(=O)O 1.91933760738618
O=C(O)C1=CC(O)=C(OC)C=C1C(=O)O 1.9183299113272931
O=C(O)C=1C=CC=CC1C(=O)C2=CC=C(C(=O)O)C(=C2)C(=O)O 1.9180842048554672
O=C(O)C1=CC=C(C=C1C(=O)O)NC(=O)C=2C=CN=CC2 1.9178503177387105
O=C(O)C1=CC=C(C=C1C(=O)O)C 1.9158248601619663
O=C(O)C1=CC=C(C=C1C(=O)O)C(C)(C)C 1.9157554289894807
O=C(O)C1=CC=C(O)C=C1C(=O)O 1.9156093879409548
O=C(O)C1=CC=C(C=C1C(=O)O)C=2C=CC(C(=O)O)=C(C2)C(=O)O 1.9156079566802964
O=C(O)C=1C=CC(=CC1C(=O)O)C=2C=CC=CC2 1.915265261264943
O=C(O)C1=CC(F)=C(C=C1C(=O)O)C(F)(F)F 1.914630542025736
O=C(O)C=1C=C2C(=CC1C(=O)O)C3C=4C=CC=CC4C2C5=CC(C(=O)O)=C(C=C53)C(=O)O 1.9139366095254304
O=C(O)C1=CC(Cl)=C(C=C1C(=O)O)C(F)(F)F 1.912664483228586
O=C(O)C1=CC=C(C=C1C(=O)O)CC(NC(=O)OC(C)(C)C)C 1.9126143200435
O=C(O)C1=CC=C(OC2CC2)C=C1C(=O)O 1.911073256634676
O=C(O)C=1C=C(C(=O)O)C(=CC1Cl)C(=O)O 1.9092145386949075
O=C(O)C=1C=C2C=C3C=CC=CC3=CC2=CC1C(=O)O 1.9090602702354955
O=C(O)C1=CC=C(OC=2C=CC=CC2)C=C1C(=O)O 1.9089600500876245
O=C(O)C=1C=C(C(=CC1C(=O)O)CC)CC 1.9088631461438488
O=C(O)C1=CC=C(OC2=CC=CC(N)=C2)C=C1C(=O)O 1.9078809671382344
O=C(O)C1=CC=C(OC)C=C1C(=O)O 1.9078632003055016
O=C(O)C=1C=C(C(=CC1C(=O)O)C)C 1.906444718914607
O=C(O)C=1C=C(C(=CC1C(=O)O)C(C)C)C 1.9061617794074373
O=C(O)C1=CC=C(C=C1C(=O)O)CNC(=O)OC(C)(C)C 1.9057923214944477
O=C(O)C=1C=C(C(=O)O)C(=CC1Br)C(=O)O 1.904189750110562
O=C(O)C1=CC=2C=CC=CC2C=C1C(=O)O 1.9024688081711556
O=C(O)C1=CC(Br)=C(Br)C=C1C(=O)O 1.90216855873804
O=C(O)C1=CC=C(C=C1C(=O)O)C(=O)OCC 1.9020163874912788
O=C(O)C=1C=C2C(=CC1C(=O)O)CN(C(=O)OC(C)(C)C)C2 1.8990909030451089
O=C(O)C1=CC(Cl)=C(Br)C=C1C(=O)O 1.8985674339085457
O=C(O)C1=CC=C(C=C1C(=O)O)C(N)C(=O)O 1.8974844074235104
O=C(O)C1=CC=C(C=C1C(=O)O)B(O)O 1.896855746281696
O=C(O)C1=CC=C(OC2=CC=C(C(=O)O)C(=C2)C(=O)O)C=C1 1.8966996759426256
O=C(O)C1=CC=C(OC2=CC=C(C=C2)C(C3=CC=C(OC4=CC=CC(C(=O)O)=C4C(=O)O)C=C3)(C)C)C=C1C(=O)O 1.8947281452836604
O=C(O)C=1C=C2N=CC=CC2=CC1C(=O)O 1.8946539100754136
O=C(O)C1=CC=C(C=C1C(=O)O)C(N)C(=O)O 1.8943806849416167
O=C(O)C1=CC(F)=C(Br)C=C1C(=O)O 1.8935048821018845
O=C(O)C1=CC(OC2=CC=C(C(=O)O)C(=C2)C(=O)O)=CC(=C1)C(=O)O 1.8918710519268416
O=C(O)C=1C=C(C=C(C1)C2=CC=C(C(=O)O)C(=C2)C(=O)O)C(=O)O 1.8917011710005995
O=C(O)C=1C=C(C(=O)O)C(=CC1O)C(=O)O 1.8906351961647296
O=C(O)C1=CC=C(C=C1C(=O)O)C(F)(F)F 1.889629666483696
O=C(O)C1=CC=C(C=C1C(=O)O)C(N)C(=O)O 1.888916216206866

In [12]:
df[["cas", "sigma"]]

              cas     sigma
0       2300-16-5  2.930214
1      90348-28-0  2.768664
2       6219-66-5  2.747609
3      92971-15-8  2.659946
4      14597-16-1  2.515757
..            ...       ...
171   499793-28-1  1.891871
172  1868072-45-0  1.891701
173     4961-03-9  1.890635
174      835-58-5  1.889630
175   201730-10-1  1.888916

[176 rows x 2 columns]

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF, ConstantKernel, WhiteKernel
from sklearn.model_selection import LeaveOneOut
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
import joblib

df = pd.read_csv(
    r"C:\Users\kkyom\OneDrive\デスクトップ\pka_activity\ver_3\out\save\value.csv"
)

df = df.dropna(how="any").reset_index(drop=True)

descriptors = [
    "dipole_moment_debye",
    "3and6",
    "lumo_ev",
    "homo_ev",
]


length = len(descriptors)
X = df[descriptors]
y = df["yield"]
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
kernel = (
    ConstantKernel() * RBF([1.0] * length, length_scale_bounds=(1e-2, 1e10))
    + WhiteKernel()
)
model = GaussianProcessRegressor(
    kernel=kernel, n_restarts_optimizer=10, random_state=42
)
loo = LeaveOneOut()
y_true, y_pred = [], []
for i, (train_index, test_index) in enumerate(loo.split(X_scaled)):
    X_train, X_test = X_scaled[train_index], X_scaled[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]
    model.fit(X_train, y_train)

    y_pred.append(model.predict(X_test)[0])
    y_true.append(y_test.values[0])

    if i < 5:  # 最初の5回だけ表示
        print(f"Iter {i}: Kernel params = {model.kernel_}")
        # もしHOMO（4変数版の4番目）のLength Scaleが小さくなっている回があれば、
        # そのデータにとってはHOMOが「超重要」だということです。

mae = mean_absolute_error(y_true, y_pred)
r2 = r2_score(y_true, y_pred)

model.fit(X_scaled, y)

Iter 0: Kernel params = 14.9**2 * RBF(length_scale=[11.3, 14.3, 8.89, 7.14e+04]) + WhiteKernel(noise_level=3.52)
Iter 1: Kernel params = 14.7**2 * RBF(length_scale=[11.2, 13.9, 8.84, 4.63e+04]) + WhiteKernel(noise_level=3.44)
Iter 2: Kernel params = 13**2 * RBF(length_scale=[10.9, 11.6, 5.5, 4.64e+04]) + WhiteKernel(noise_level=2.98)
Iter 3: Kernel params = 14.3**2 * RBF(length_scale=[9.7, 15.1, 9.96, 1.48e+04]) + WhiteKernel(noise_level=3.33)
Iter 4: Kernel params = 14.4**2 * RBF(length_scale=[11.4, 13.9, 8.12, 4.1e+04]) + WhiteKernel(noise_level=3.54)

GaussianProcessRegressor(kernel=1**2 * RBF(length_scale=[1, 1, 1, 1]) + WhiteKernel(noise_level=1),
                         n_restarts_optimizer=10, random_state=42)

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF, ConstantKernel, WhiteKernel
from sklearn.model_selection import LeaveOneOut
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
import joblib

df = pd.read_csv(
    r"C:\Users\kkyom\OneDrive\デスクトップ\pka_activity\ver_4\out\csvfile\model\samples_value.csv"
)

df = df.dropna(how="any").reset_index(drop=True)

descriptors = [
    "dipole_moment_debye",
    "3and6",
    "lumo_ev",
    "delta_g_hartree",
]


length = len(descriptors)
X = df[descriptors]
y = df["yield"]
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
kernel = (
    ConstantKernel() * RBF([1.0] * length, length_scale_bounds=(1e-2, 1e10))
    + WhiteKernel()
)
model = GaussianProcessRegressor(
    kernel=kernel, n_restarts_optimizer=10, random_state=42
)
loo = LeaveOneOut()
y_true, y_pred = [], []
for train_index, test_index in loo.split(X_scaled):
    X_train, X_test = X_scaled[train_index], X_scaled[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]
    model.fit(X_train, y_train)

    y_pred.append(model.predict(X_test)[0])
    y_true.append(y_test.values[0])

mae = mean_absolute_error(y_true, y_pred)
r2 = r2_score(y_true, y_pred)

model.fit(X_scaled, y)

content = {"model": model, "scaler": scaler}

print(r2)
print(mae)

0.48393153299996783
1.7856651862243444

In [17]:
import glob
from pathlib import Path

name = "samples"

route = Path("../out/csvfile")
filepath = next(route.glob(f"**/{name}.csv"))

print(filepath)
print(type(filepath))
filepath = str(filepath)
print(filepath)
print(type(filepath))

..\out\csvfile\model\samples.csv
<class 'pathlib.WindowsPath'>
..\out\csvfile\model\samples.csv
<class 'str'>

In [1]:
import numpy
import sys

# numpyがどこにあるか表示
print(numpy.__file__)

# Pythonが自動で探しに行くフォルダ一覧を表示
# （この中に numpy のあるフォルダが含まれているはずです）
print(sys.path)

c:\Users\kkyom\anaconda3\envs\predict_activity\Lib\site-packages\numpy\__init__.py
['C:\\Program Files\\RevvitySignalsSoftware\\ChemDrawApplications\\ChemScript\\Lib', 'C:\\Users\\kkyom\\OneDrive\\デスクトップ\\python\\stock', 'c:\\Users\\kkyom\\anaconda3\\envs\\predict_activity\\python311.zip', 'c:\\Users\\kkyom\\anaconda3\\envs\\predict_activity\\DLLs', 'c:\\Users\\kkyom\\anaconda3\\envs\\predict_activity\\Lib', 'c:\\Users\\kkyom\\anaconda3\\envs\\predict_activity', '', 'c:\\Users\\kkyom\\anaconda3\\envs\\predict_activity\\Lib\\site-packages', 'c:\\Users\\kkyom\\anaconda3\\envs\\predict_activity\\Lib\\site-packages\\win32', 'c:\\Users\\kkyom\\anaconda3\\envs\\predict_activity\\Lib\\site-packages\\win32\\lib', 'c:\\Users\\kkyom\\anaconda3\\envs\\predict_activity\\Lib\\site-packages\\Pythonwin']

In [8]:
import cclib

data = cclib.io.ccread(r"C:\Users\kkyom\OneDrive\デスクトップ\pka_activity\data\in\known\sub_652-03-9.log")
nbo_charges = data.atomcharges["natural"]
print(nbo_charges)

[-0.31799  0.34547  0.34103 -0.3187   0.40316 -0.32838 -0.15895  0.84167
 -0.68392 -0.63608 -0.1504   0.84344 -0.68426 -0.63597  0.3979  -0.32979
  0.53586  0.5359 ]

In [9]:
def get_final_nbo_charges(logfile_path):
    with open(logfile_path, 'r') as f:
        lines = f.readlines()
    
    # ファイルの最後から逆順にNBOの要約を探す
    start_line = -1
    for i in range(len(lines)-1, -1, -1):
        if "Summary of Natural Population Analysis" in lines[i]:
            start_line = i
            break
    
    if start_line == -1:
        return None

    charges = []
    # 表のヘッダーを飛ばしてデータ行（Atom No Charge... の後）へ
    # 概ね Summary... の6行後からデータが始まります
    for line in lines[start_line+6:]:
        if "---" in line or "Total" in line: # 表の終わり
            break
        parts = line.split()
        if len(parts) >= 3:
            charges.append(float(parts[2]))
    return charges

# 使用例
final_charges = get_final_nbo_charges(r"C:\Users\kkyom\OneDrive\デスクトップ\pka_activity\data\in\known\sub_652-03-9.log")

In [10]:
print(final_charges)

[-0.31591, 0.35584, 0.33016, -0.32111, 0.4162, -0.32379, -0.1797, 0.84039, -0.67774, -0.64762, -0.12747, 0.84606, -0.68202, -0.63676, 0.38437, -0.33278, 0.53628, 0.53559]

In [1]:
import calc.phthalicacid as pa
import pandas as pd

df = pd.read_excel(r"C:\Users\kkyom\OneDrive\デスクトップ\pka_activity\ver_4\data\2nd_20260204.xlsx")
df = pa.detect_phthalic_acid(df)
df

,化合物名,cas,smiles,yield,cooh
0,フタル酸,88-99-3,O=C(C1=CC=CC=C1C(O)=O)O,13.320000,"[[8, 7, 10, 9, 16], [1, 2, 0, 11, 17]]"
1,"2,3-ナフタレンジカルボン酸",2169-87-1,O=C(C1=CC2=CC=CC=C2C=C1C(O)=O)O,11.800000,"[[12, 11, 14, 13, 22], [1, 2, 0, 15, 23]]"
2,ピロメリット酸,89-05-4,O=C(C1=CC(C(O)=O)=C(C(O)=O)C=C1C(O)=O)O,11.530000,"[[9, 8, 11, 10, 20], [5, 4, 7, 6, 19]]"
3,4-ニトロフタル酸,610-27-5,O=C(O)C1=CC=C(C=C1C(=O)O)N(=O)=O,15.650000,"[[9, 8, 10, 11, 19], [1, 3, 0, 2, 15]]"
4,3-ニトロフタル酸,603-11-2,O=C(O)C1=CC=CC(=C1C(=O)O)N(=O)=O,12.490000,"[[9, 8, 10, 11, 19], [1, 3, 0, 2, 15]]"
5,TE,te,O=C(C(C=C1)=C(C(O)=O)C=C1OC2=CC(OC3=CC=C(C(O)=...,4.180000,"[[6, 5, 8, 7, 47], [1, 2, 0, 44, 62]]"
6,DE,de,O=C(C(C=C1)=C(C(O)=O)C=C1OC2=CC=CC(OC3=CC(C(O)...,11.500000,"[[6, 5, 8, 7, 34], [1, 2, 0, 31, 45]]"
7,EE,ee,O=C(C1=CC(OC(C=C2)=CC=C2OC3=CC(OC4=CC=C(OC5=CC...,8.735648,"[[42, 41, 44, 43, 66], [1, 2, 0, 45, 67]]"
8,"アントラキノン-2,3-ジカルボン酸",27485-15-0,O=C1C2=C(C=C(C(O)=O)C(C(O)=O)=C2)C(C3=CC=CC=C3...,17.690000,"[[6, 5, 8, 7, 23], [10, 9, 12, 11, 24]]"
9,4-メトキシフタル酸,1885-13-8,COC1=CC=C(C(O)=O)C(C(O)=O)=C1,13.290000,"[[6, 5, 8, 7, 19], [10, 9, 12, 11, 20]]"
10,3-メトキシフタル酸,14963-97-4,COC1=C(C(O)=O)C(C(O)=O)=CC=C1,8.950000,"[[4, 3, 6, 5, 17], [8, 7, 10, 9, 18]]"
11,4-NO,4-no,O=C(C1=CC(OC2=CC3=CC=CC=C3C=C2)=CC=C1C(O)=O)O,12.970000,"[[19, 18, 21, 20, 33], [1, 2, 0, 22, 34]]"
12,4-PO,4-po,O=C(C1=CC(OC2=CC3=C4C(C=CC5=CC=CC(C=C3)=C54)=C...,13.900000,"[[25, 24, 27, 26, 41], [1, 2, 0, 28, 42]]"
13,4-NE,4-ne,O=C(C(C=C1)=C(C(O)=O)C=C1OCCOC2=CC3=CC=CC=C3C=...,12.800000,"[[6, 5, 8, 7, 28], [1, 2, 0, 25, 41]]"
14,3-NE,3-ne,O=C(C1=CC=CC(OCCOC2=CC3=CC=CC=C3C=C2)=C1C(O)=O)O,5.700000,"[[22, 21, 24, 23, 40], [1, 2, 0, 25, 41]]"
15,4-PE,4-pe,O=C(C(C=C1)=C(C(O)=O)C=C1OCCOC2=CC3=C4C(C=CC5=...,13.550000,"[[6, 5, 8, 7, 34], [1, 2, 0, 31, 49]]"
16,4-NB,4-nb,O=C(C(C=C1)=C(C(O)=O)C=C1OCCCCOC2=CC3=CC=CC=C3...,13.460000,"[[6, 5, 8, 7, 30], [1, 2, 0, 27, 47]]"
17,"4,5-ジクロロフタル酸",56962-08-4,ClC1=C(Cl)C=C(C(O)=O)C(C(O)=O)=C1,18.180000,"[[6, 5, 8, 7, 15], [10, 9, 12, 11, 16]]"
18,ベンゾフェノンテトラカルボン酸,2479-49-4,O=C(C1=CC(C(O)=O)=C(C(O)=O)C=C1)C2=CC=C(C(O)=O...,14.760000,"[[9, 8, 11, 10, 28], [5, 4, 7, 6, 27]]"
19,イミダゾール,10351-75-4,O=C(C1=CC2=C(C=C1C(O)=O)N=CN2)O,7.200000,"[[8, 7, 10, 9, 17], [1, 2, 0, 14, 20]]"
20,"4,5-ジフルオロフタル酸",18959-31-4,FC1=C(F)C=C(C(O)=O)C(C(O)=O)=C1,14.920000,"[[6, 5, 8, 7, 15], [10, 9, 12, 11, 16]]"
21,3-クロロフタル酸,27563-65-1,ClC1=C(C(O)=O)C(C(O)=O)=CC=C1,10.000000,"[[3, 2, 5, 4, 13], [7, 6, 9, 8, 14]]"
22,テトラフルオロフタル酸,652-03-9,FC1=C(F)C(F)=C(C(O)=O)C(C(O)=O)=C1F,10.920000,"[[7, 6, 9, 8, 16], [11, 10, 13, 12, 17]]"
23,トリメリット酸,528-44-9,O=C(O)C1=CC=C(C(=O)O)C(=C1)C(=O)O,11.820000,"[[7, 6, 8, 9, 18], [12, 10, 13, 14, 20]]"
24,"Bis(3,4-dicarboxyphenyl)methane",10595-33-2,O=C(O)C1=CC=C(C=C1C(=O)O)CC2=CC=C(C(=O)O)C(=C2...,9.430000,"[[9, 8, 10, 11, 29], [1, 3, 0, 2, 25]]"

In [9]:
from rdkit import Chem

def test(smiles):
    mol = Chem.MolFromSmiles(smiles)
    mol = Chem.AddHs(mol)  # 水素を追加
    phthalic_pattern = Chem.MolFromSmarts("c1ccc(C(=O)O)c(C(=O)O)c1")
    # フタル酸構造を持つかどうか
    matches_data = mol.GetSubstructMatches(phthalic_pattern)
    print("matches_data:", matches_data)
    oh_list = []
    cooh_list = []
    if matches_data:
        num = 0
        while True:
            # 2つ以上フタル酸構造を含まれていることを考慮して一つだけ検出
            matches = matches_data[num]
            for match in matches:
                atom = mol.GetAtomWithIdx(match)  # その番号の原子の情報
                symbol = atom.GetSymbol()  # その番号の原子
                # まだこの時点では水素の場所は検出されていないのでカルボン酸の水素を検出
                if symbol == "O":
                    neighbors = atom.GetNeighbors()  # その原子に隣接する原子の情報
                    elements = [n.GetSymbol() for n in neighbors]
                    if "H" in elements and "C" in elements:
                        for neighbor in neighbors:
                            if neighbor.GetSymbol() == "H":
                                oh_list.append((atom.GetIdx(), neighbor.GetIdx()))
            # 片側もしくは両側がエステルになっている場合を考慮
            if len(oh_list) < 2:
                num += 1
                oh_list = []
                continue
            idx = matches
            for match in matches:
                atom = mol.GetAtomWithIdx(match)
                symbol = atom.GetSymbol()
                # カルボン酸の炭素を起点に他の原子を検出
                if symbol == "C":
                    neighbors = atom.GetNeighbors()
                    elements = [n.GetSymbol() for n in neighbors]
                    if elements.count("O") >= 2:
                        for neighbor in neighbors:
                            if neighbor.GetSymbol() == "C":
                                c = neighbor.GetIdx()
                            elif neighbor.GetSymbol() == "O":
                                if len(neighbor.GetNeighbors()) == 1:
                                    o_double = neighbor.GetIdx()
                                elif len(neighbor.GetNeighbors()) == 2:
                                    for oh in oh_list:
                                        if oh[0] == neighbor.GetIdx():
                                            o_single = oh[0]
                                            h = oh[1]
                        # 自身の炭素原子、それに結合しているベンゼン環内の炭素原子、
                        # 炭素と2重結合している酸素原子、炭素と単結合している酸素原子、水素の順
                        cooh_list.append([atom.GetIdx(), c, o_double, o_single, h])
            break
    print(cooh_list)

test("O=C(C1=C(C(O)=O)C=CC(CC2=CC=C(C(O)=O)C(C(O)=O)=C2)=C1)O")
test("FC1=C(F)C(F)=C(C(O)=O)C(C(O)=O)=C1F")

matches_data: ((8, 9, 23, 2, 1, 0, 24, 3, 4, 6, 5, 7), (11, 12, 13, 14, 15, 17, 16, 18, 19, 21, 20, 22))
[[1, 2, 0, 24, 36], [4, 3, 6, 5, 25]]
matches_data: ((1, 2, 4, 6, 7, 9, 8, 10, 11, 13, 12, 14),)
[[7, 6, 9, 8, 16], [11, 10, 13, 12, 17]]

In [4]:
import pandas as pd

df = pd.read_csv(r"C:\Users\kkyom\OneDrive\デスクトップ\pka_activity\ver_4\out\csvfile\descriptors\2nd_20260205.csv")
df = df.sort_values("r2", ascending=False)
print(df)
df.to_csv(r"C:\Users\kkyom\OneDrive\デスクトップ\pka_activity\ver_4\out\csvfile\descriptors\2nd_20260205.csv", index=False)

                                       descriptor       mae        r2
1093         lumo_ev|dipole_moment_debye|sasa|hbd  1.159665  0.742361
689               homo_ev|gap_ev|h_nbo_charge|hbd  1.184148  0.740099
1495  omega|molecular_volume_A3|h_nbo_charge|logp  1.191498  0.726798
1478           omega|dipole_moment_debye|sasa|hbd  1.129345  0.711483
1542                  omega|h_nbo_charge|sasa|hbd  1.351712  0.699656
...                                           ...       ...       ...
1821         h_nbo_charge|o_nbo_charge|sasa|4and5  3.542620 -1.171583
1902                  o_nbo_charge|4and5|logp|hba  3.593357 -1.188514
1829         h_nbo_charge|o_nbo_charge|4and5|logp  3.671908 -1.191000
1689  dipole_moment_debye|o_nbo_charge|4and5|logp  3.879952 -1.322903
1429                       gap_ev|sasa|4and5|logp  3.338181 -1.500530

[1940 rows x 3 columns]

In [6]:
a = "1-100"
b,c = a.split("-")
print(type(b),c)

<class 'str'> 100

In [12]:
import pandas as pd

df = pd.read_csv(r"C:\Users\kkyom\OneDrive\デスクトップ\pka_activity\ver_4\out\csvfile\predict\2nd_20260211_4.csv")
df = df[["smiles", "cas", "mu", "sigma"]]
df = df.sort_values("sigma", ascending=False, ignore_index=True)
for i in range(len(df)):
    print(df.loc[i, "smiles"])

O=C(O)C=1C(C(=O)O)=C(C(C(=O)O)=C(C(=O)O)C1C(F)(F)F)C(F)(F)F
O=C(O)C1=C(O)C=C2C(=O)C3=C(O)C(O)=C(C(O)=C3C(=O)C2=C1C(=O)O)C4=CC(=CC=C4O)CCN
O=C(O)C1=CC=C2C(=C1C(=O)O)C(C=3C=CC=CC3)(C)CC2(C)C
O=C(O)C1=C(OCC)C=2C=CC=CC2C(OCC)=C1C(=O)O
O=C(O)C=1C=C(C(=O)O)C(C(=O)O)=C(C(=O)O)C1C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)C(NC(=O)OC(C=2C=CC=CC2N(=O)=O)C)C(=O)O
O=C(O)C1=C(O)C=C2C(=O)C=3C(O)=C(C(C(=O)C)=C(O)C3C(=O)C2=C1C(=O)O)CC
O=C(O)C=1C(Cl)=CC=C(C1C(=O)O)C(F)(F)F
O=C(O)C1=C(C(=O)O)C(=CC=C1C)C
O=C(O)C1=C(C(=O)O)C(=CC=C1N(=O)=O)N(=O)=O
O=C(O)C1=CC=CC(=C1C(=O)O)S(=O)(=O)N
O=C(O)C1=CC(N=NC=2C=C(C(=O)O)C(C(=O)O)=C(C2)C(=O)O)=CC(C(=O)O)=C1C(=O)O
O=C(O)C1=CC=CC(C=2C=CC=CC2C)=C1C(=O)O
O=C(O)C=1C(Br)=C(C(=O)O)C(C(=O)O)=C(Br)C1C(=O)O
O=C(O)C=1C(Br)=C(Br)C(Br)=C(Br)C1C(=O)O
O=C(O)C=1C(Br)=CC=C(Br)C1C(=O)O
O=C(O)C=1C=C(C(=O)O)C(C(=O)O)=C(C1C(=O)O)C(F)(F)F
O=C(O)C=1C=CC=C(NO)C1C(=O)O
O=C(O)C1=CC(Cl)=C(C(=O)O)C(C(=O)O)=C1Cl
O=C(O)C1=CC=C(C(=O)O)C(C(=O)O)=C1C(=O)O
O=C(O)C1=CC=C(C=C1)C=2C=CC=C(C(=O)O)C2C(=O)O
O=C(O)C1=CC(O)=CC(C(=O)O)=C1C(=O)O
O=C(O)C1=CC=CC(C=2C=CC=CC2)=C1C(=O)O
O=C(O)C=1C=CC=C(N=N(=O)C=2C=CC=C(C(=O)O)C2C(=O)O)C1C(=O)O
O=C(O)C1=CC(N)=CC(C(=O)O)=C1C(=O)O
O=C(O)C=1C(Cl)=CC=C(Cl)C1C(=O)O
O=C(O)C=1C=CC=C(C=C)C1C(=O)O
O=C(O)C=1C(Cl)=C(Cl)C(Cl)=C(Cl)C1C(=O)O
O=C(O)C=1C(Cl)=CC(Cl)=C(Cl)C1C(=O)O
O=C(O)C1=CC=C(C(=C1C(=O)O)N(=O)=O)N(=O)=O
O=C(O)C=1C=C(C(=O)O)C(C(=O)O)=C(C1)C(=O)O
O=C(O)C=1C(F)=CC=C(C1C(=O)O)C
O=C(O)C=1C(O)=CC=C(O)C1C(=O)O
O=C(O)C=1C=C(C(=CC1C(=O)O)N(=O)=O)N(=O)=O
O=C(O)C=1C=C(C=C(C(=O)O)C1C(=O)O)N(=O)=O
O=C(O)C1=CC(O)=C(C(=O)O)C(=C1C(=O)O)C
O=C(O)C=1C=CC=C(NC(=O)OCC2C=3C=CC=CC3C=4C=CC=CC42)C1C(=O)O
O=C(O)C1=CC=CC(C(=O)O)=C1C(=O)O
O=C(O)C=1C=CC=C(NN)C1C(=O)O
O=C(O)C1=CC(OC)=CC(=C1C(=O)O)C
O=C(O)C1=CC=C(C(NC(=O)C)=C1C(=O)O)N(=O)=O
O=C(O)C=1C=C(C=C(C1C(=O)O)N(=O)=O)N(=O)=O
O=C(O)C1=CC(OC)=C(OC)C(OC)=C1C(=O)O
N#CC=1C=C(C(=O)O)C(=CC1C#N)C(=O)O
O=C(O)C1=CC=C(F)C(=C1C(=O)O)C(F)(F)F
O=C(O)C=1C(F)=CC=C(Br)C1C(=O)O
O=C(O)C=1C=CC=C(NCC=2SC=CC2)C1C(=O)O
O=C(O)C=1C=CC=C(NCC=2C=NC=CC2)C1C(=O)O
O=C(O)C1=CC=C(O)C(O)=C1C(=O)O
O=C(O)C=1C=C(C(=O)O)C(=CC1C(=O)O)S(=O)(=O)O
O=C(O)C1=CC=C(OC2=CC=C(C=C2)N(=O)=O)C=C1C(=O)O
O=C(O)C=1C=C(C=C(C1C(=O)O)C)C
O=C(O)C1=CC=C(N=NC2=CC=C(C(=O)O)C(=C2)C(=O)O)C=C1C(=O)O
O=C(O)C=1C(OC)=CC=C(OC)C1C(=O)O
O=C(O)C=1C=CC=C(NCC=2OC(=CC2)C)C1C(=O)O
O=C(O)C1=CC(O)=C(C(=O)O)C(=C1)C(=O)O
O=C(O)C1=CC=C(Cl)C(=C1C(=O)O)N(=O)=O
O=C(O)C1=CC=C(C=C1C(=O)O)S(=O)(=O)C2=CC=C(C(=O)O)C(=C2)C(=O)O
O=C(O)C1=CC=CC(=C1C(=O)O)C
O=C(O)C1=CC=C(F)C(=C1C(=O)O)N(=O)=O
O=C(O)C=1C=C(C(=O)O)C(=CC1C(=O)O)N(=O)=O
O=C(O)C1=CC(N)=C(C=C1C(=O)O)N(=O)=O
O=C(O)C1=CC=C(C=C1C(=O)O)C(=O)C2=CC=C(C=C2)C(=O)C3=CC=C(C(=O)O)C(=C3)C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)NN
O=C(O)C1=CC=C(OC2=CC=CC(C(=O)O)=C2C(=O)O)C=C1
O=C(O)C1=CC=C(C(N)=C1C(=O)O)C
O=C(O)C1=CC=CC(=C1C(=O)O)N(=O)=O
O=C(O)C=1C=CC=C(N)C1C(=O)O
O=C(O)C1=C(F)C(F)=C(O)C(F)=C1C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)S(=O)(=O)N
O=C(O)C=1C=CC=C(NCC2CC2)C1C(=O)O
O=C(O)C=1C=CC=C(OCC2=CC=C(C=C2)CO)C1C(=O)O
O=C(O)C=1C=CC=C(NC(=O)OC(C)(C)C)C1C(=O)O
O=NC1=CC=CC(C(=O)O)=C1C(=O)O
O=C(O)C1=CC(F)=CC(=C1C(=O)O)C
O=C(O)C1=CC=C(F)C(Br)=C1C(=O)O
O=C(O)C1=CC=C(C(OC)=C1C(=O)O)C
O=C(O)C1=CC=C(C=C1C(=O)O)N(=O)=O
O=C(O)C=1C=C(C(=O)O)C(=CC1N)C(=O)O
O=C(O)C1=CC=C(OC)C(OC)=C1C(=O)O
O=C(O)C=1C=CC=C(OC2=CC=CC(C(=O)O)=C2C(=O)O)C1
O=C(O)C1=CC(N)=C(N)C=C1C(=O)O
O=C(O)C=1C=CC=C(NCC)C1C(=O)O
O=C(O)C=1C=C(C(=O)O)C(=CC1C(=O)O)C(=O)C=2C=CC=CC2
O=C(O)C1=CC=C(C=C1C(=O)O)C(=O)C2=CC=C(C(=O)O)C(=C2)C(=O)O
O=C(O)C=1C=CC=C(Br)C1C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)S(=O)(=O)O
O=C(O)C=1C=C2C=C3C=C(C(=O)O)C(=CC3=CC2=CC1C(=O)O)C(=O)O
O=C(O)C1=CC(O)=C(N)C=C1C(=O)O
O=C(O)C1=CC=C(OC2=CC=C(C(=O)O)C(=C2)C(=O)O)C=C1C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)C(=O)OCCOC(=O)C(=C)C
O=C(O)C=1C=C(C=C(C1)C2=CC=C(C(=O)O)C(=C2)C(=O)O)C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)N2C(=O)C=CC2=O
O=C(O)C1=CC=C(OC2=CC=CC(OC3=CC=C(C(=O)O)C(=C3)C(=O)O)=C2)C=C1C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)C(=O)C=2C=CC=CC2
N#CC1=CC=C(C(=O)O)C(=C1)C(=O)O
O=C(O)C=1C=C(C(=O)O)C(=CC1C(=O)O)C(=O)O
O=C(O)C1=CC=C(Cl)C(Cl)=C1C(=O)O
O=CC1=CC=C(C(=O)O)C(=C1)C(=O)O
O=C(Cl)C1=CC=C(C(=O)O)C(=C1)C(=O)O
O=C(O)C=1C(F)=CC=C(F)C1C(=O)O
O=C(O)C1=CC=2C=CNC2C=C1C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)C=2C=CC(C(=O)O)=C(C2)C(=O)O
O=C(O)C1=CC=2N=CNC2C=C1C(=O)O
O=C(O)C=1C=C(Cl)C=C(Cl)C1C(=O)O
O=C(O)C1=CC=C(OS(=O)(=O)C=2C=CC=CC2)C=C1C(=O)O
O=C(O)C1=CC(Cl)=C(Cl)C(Cl)=C1C(=O)O
O=C(O)C1=CC(OC)=C(Cl)C(Cl)=C1C(=O)O
O=C(O)C=1C=CC=C(Cl)C1C(=O)O
O=C(O)C1=CC=C2N=CC=CC2=C1C(=O)O
O=C(O)C1=CC(OC2=CC=C(C(=O)O)C(=C2)C(=O)O)=CC(=C1)C(=O)O
O=C(O)C1=CC(Br)=CC(Cl)=C1C(=O)O
O=C(O)C=1C=CC=2C=CC=CC2C1C(=O)O
O=C(O)C=1C=CC=C(OC2=CC=C(C=C2)C)C1C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)C(C2=CC=C(C(=O)O)C(=C2)C(=O)O)(C(F)(F)F)C(F)(F)F
O=C(O)C=1C=C2C(=CC1C(=O)O)C3C=4C=CC=CC4C2C5=CC(C(=O)O)=C(C=C53)C(=O)O
O=C(O)C1=CC(Cl)=C(C=C1C(=O)O)C(F)(F)F
O=C(O)C=1C=C(C(=CC1C(=O)O)CC)CC
O=C(O)C=1C=CC(=CC1)C2=CC(C(=O)O)=C(C=C2C3=CC=C(C=C3)C(=O)O)C(=O)O
O=C(O)C1=CC(OC)=C(OC)C=C1C(=O)O
O=C(O)C=1C=C2C=C3C=CC=CC3=CC2=CC1C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)C(N)C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)CNC(=O)OC(C)(C)C
O=C(O)C1=CC=C(C=C1C(=O)O)NC(=O)C=2C=CN=CC2
O=C(O)C1=CC=C(C=C1C(=O)O)C(N)C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)B(O)O
O=C(O)C=1C=CC=C(O)C1C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)C(=O)OCC
O=C(O)C1=CC=C(OC2=CC=C(C=C2)C(C3=CC=C(OC4=CC=CC(C(=O)O)=C4C(=O)O)C=C3)(C)C)C=C1C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)NC(=O)C
O=C(O)C=1C=CC=CC1C(=O)C2=CC=C(C(=O)O)C(=C2)C(=O)O
O=C(O)C1=CC=C(C#CC=2C=CC=CC2)C=C1C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)C(N)C(=O)O
O=C(O)C=1C=C(C(=O)O)C(=CC1O)C(=O)O
O=C(O)C1=CC(F)=C(C=C1C(=O)O)C(F)(F)F
O=C(O)C1=CC=C(C#C)C=C1C(=O)O
O=C(O)C1=CC=C(O)C=C1C(=O)O
O=C(O)C1=CC=C(C(=O)O)C(=C1)C(=O)O
O=C(O)C1=CC=C(S)C=C1C(=O)O
O=C(O)C=1C=C2N=CC=CC2=CC1C(=O)O
O=C(O)C=1C=CC(=CC1C(=O)O)C=2C=CC=CC2
O=C(O)C1=CC=C(OC2=CC=C(N)C=C2)C=C1C(=O)O
O=C(O)C=1C=C(C(=O)O)C(=CC1Cl)C(=O)O
O=C(O)C1=CC(Br)=CC(F)=C1C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)NC(=O)OC(C)(C)C
O=C(O)C1=CC=C(OCC)C=C1C(=O)O
O=C(O)C=1C=C(C(=O)O)C(=CC1Br)C(=O)O
O=C(O)C1=CC=C(C=C)C=C1C(=O)O
O=C(O)C=1C=C(F)C=C(F)C1C(=O)O
O=C(O)C1=CC(Br)=C(Br)C=C1C(=O)O
O=C(O)C1=CC=C(Br)C(F)=C1C(=O)O
O=C(O)C1=CC=C(OC2CC2)C=C1C(=O)O
O=C(O)C1=CC=C(OC(C)C)C=C1C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)CC(NC(=O)OC(C)(C)C)C
O=C(O)C1=CC(O)=C(OC)C=C1C(=O)O
O=C(O)C1=CC(Cl)=C(Br)C=C1C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)C(F)(F)F
O=C(O)C=1C=CC=C(OC)C1C(=O)O
O=C(O)C1=CC=C(F)C=C1C(=O)O
O=C(O)C=1C=C(OC)C=C(OC)C1C(=O)O
O=C(O)C=1C=CC=CC1C(=O)O
O=C(O)C1=CC=C(OC2=CC=CC(N)=C2)C=C1C(=O)O
O=C(O)C1=CC=C(OC2=CC=C(C(=O)O)C(=C2)C(=O)O)C=C1
O=C(O)C1=CC=C(OC=2C=CC=CC2)C=C1C(=O)O
O=C(O)C1=CC=C(Br)C=C1C(=O)O
O=C(O)C1=CC=C(Cl)C=C1C(=O)O
O=C(O)C1=CC=C(OC)C=C1C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)C(C)(C)C
O=C(O)C=1C=CC=C(F)C1C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)C
O=C(O)C=1C=C(C(=CC1C(=O)O)C(C)C)C
O=C(O)C=1C=C(C(=CC1C(=O)O)C)C
O=C(O)C1=CC(F)=C(Br)C=C1C(=O)O
O=C(O)C1=CC=C(F)C(F)=C1C(=O)O
O=C(O)C1=CC=2C=CC=CC2C=C1C(=O)O
O=C(O)C=1C=C2C(=CC1C(=O)O)CN(C(=O)OC(C)(C)C)C2

In [1]:
import pandas as pd

df = pd.read_csv(r"C:\Users\kkyom\OneDrive\デスクトップ\pka_activity\ver_4\out\csvfile\descriptors\gauss_train.csv")
df = df.sort_values("r2", ascending=False)
df.to_csv(r"C:\Users\kkyom\OneDrive\デスクトップ\pka_activity\ver_4\out\csvfile\descriptors\1st_20260221.csv", index=False)

In [2]:
import pandas as pd

df = pd.read_csv(r"C:\Users\kkyom\OneDrive\デスクトップ\pka_activity\ver_4\out\csvfile\predict\1st_20260204.csv")
for i in range(len(df)):
    print(df.loc[i, "smiles"])

O=C(O)C=1C=CC=CC1C(=O)O
O=C(O)C1=CC=CC(=C1C(=O)O)N(=O)=O
O=C(O)C1=CC=C(O)C=C1C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)N(=O)=O
O=C(O)C1=CC=C(C(=O)O)C(=C1)C(=O)O
O=C(O)C=1C=C(C(=O)O)C(=CC1C(=O)O)C(=O)O
O=C(O)C1=CC=C(OC)C=C1C(=O)O
O=C(O)C1=CC=CC(C(=O)O)=C1C(=O)O
O=C(O)C1=CC=C(Br)C=C1C(=O)O
O=C(O)C=1C=CC=C(F)C1C(=O)O
O=C(O)C1=CC(Cl)=C(C(=O)O)C(C(=O)O)=C1Cl
O=C(O)C=1C(F)=CC=C(F)C1C(=O)O
O=C(O)C1=CC=C(F)C=C1C(=O)O
O=C(O)C=1C=CC=C(N)C1C(=O)O
O=C(O)C1=CC=2C=CC=CC2C=C1C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)C=2C=CC(C(=O)O)=C(C2)C(=O)O
O=C(O)C=1C=CC=C(Br)C1C(=O)O
O=C(O)C=1C(O)=CC=C(O)C1C(=O)O
O=C(O)C1=CC=C(Cl)C=C1C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)C
O=C(O)C=1C=CC=C(OC)C1C(=O)O
O=C(O)C1=CC=2N=CNC2C=C1C(=O)O
O=C(O)C=1C(Cl)=C(Cl)C(Cl)=C(Cl)C1C(=O)O
O=C(O)C1=CC(N)=CC(C(=O)O)=C1C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)C(F)(F)F
O=C(O)C1=CC=CC(=C1C(=O)O)C
O=C(O)C1=CC=C(C=C1C(=O)O)C(N)C(=O)O
O=C(O)C=1C=C(C(=O)O)C(C(=O)O)=C(C(=O)O)C1C(=O)O
O=C(O)C=1C=CC=C(O)C1C(=O)O
O=C(O)C=1C=CC=C(Cl)C1C(=O)O
O=C(O)C=1C=C(C=C(C(=O)O)C1C(=O)O)N(=O)=O
O=C(O)C1=CC=C(C=C1C(=O)O)C(=O)C2=CC=C(C(=O)O)C(=C2)C(=O)O
O=C(O)C1=CC(Br)=C(Br)C=C1C(=O)O
O=C(O)C=1C=C(C(=O)O)C(=CC1C(=O)O)C(=O)C=2C=CC=CC2
O=C(O)C1=CC(OC)=C(OC)C=C1C(=O)O
O=C(O)C1=CC=C(OC2=CC=C(C(=O)O)C(=C2)C(=O)O)C=C1C(=O)O
O=C(O)C=1C=C(C(=CC1C(=O)O)C)C
O=C(O)C1=CC=C(C=C1C(=O)O)B(O)O
O=C(O)C1=CC=C(C=C1C(=O)O)C(C)(C)C
O=C(O)C1=CC=C(Br)C(F)=C1C(=O)O
O=C(O)C1=CC(Br)=CC(F)=C1C(=O)O
O=C(O)C=1C(Cl)=CC(Cl)=C(Cl)C1C(=O)O
O=C(O)C=1C(Br)=C(C(=O)O)C(C(=O)O)=C(Br)C1C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)C(C2=CC=C(C(=O)O)C(=C2)C(=O)O)(C(F)(F)F)C(F)(F)F
O=C(O)C1=CC=C(C=C1C(=O)O)S(=O)(=O)O
O=C(O)C1=CC=C(OC=2C=CC=CC2)C=C1C(=O)O
O=C(O)C1=CC=C(Cl)C(Cl)=C1C(=O)O
O=C(O)C1=CC=C(C#C)C=C1C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)N2C(=O)C=CC2=O
O=C(O)C=1C=CC=C(NC(=O)OC(C)(C)C)C1C(=O)O
O=C(O)C1=CC=C(F)C(Br)=C1C(=O)O
O=C(O)C=1C=C(Cl)C=C(Cl)C1C(=O)O
O=C(O)C=1C(F)=CC=C(Br)C1C(=O)O
O=C(O)C=1C(Cl)=CC=C(Cl)C1C(=O)O
O=C(O)C1=CC(Cl)=C(Cl)C(Cl)=C1C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)CNC(=O)OC(C)(C)C
O=C(O)C=1C=C2C=C3C=CC=CC3=CC2=CC1C(=O)O
O=C(O)C1=CC=C(C(=C1C(=O)O)N(=O)=O)N(=O)=O
O=C(O)C1=CC=C(OC2=CC=CC(OC3=CC=C(C(=O)O)C(=C3)C(=O)O)=C2)C=C1C(=O)O
O=C(O)C=1C=C2C(=CC1C(=O)O)CN(C(=O)OC(C)(C)C)C2
O=C(O)C=1C=CC(=CC1)C2=CC(C(=O)O)=C(C=C2C3=CC=C(C=C3)C(=O)O)C(=O)O
O=C(O)C1=CC=C(N=NC2=CC=C(C(=O)O)C(=C2)C(=O)O)C=C1C(=O)O
O=C(O)C=1C=C(C(=O)O)C(=CC1C(=O)O)S(=O)(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)C(=O)C=2C=CC=CC2
O=C(O)C=1C=C(C=C(C1)C2=CC=C(C(=O)O)C(=C2)C(=O)O)C(=O)O
O=C(O)C1=CC(OC)=C(OC)C(OC)=C1C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)NC(=O)C=2C=CN=CC2
O=C(O)C1=CC=C(C(=O)O)C(C(=O)O)=C1C(=O)O
O=C(O)C1=CC=C(F)C(F)=C1C(=O)O
O=C(O)C1=CC(Cl)=C(Br)C=C1C(=O)O
O=C(O)C=1C(Br)=C(Br)C(Br)=C(Br)C1C(=O)O
O=C(O)C1=CC(OC2=CC=C(C(=O)O)C(=C2)C(=O)O)=CC(=C1)C(=O)O
O=C(O)C=1C=C(C(=CC1C(=O)O)N(=O)=O)N(=O)=O
O=C(O)C1=CC=C(OC)C(OC)=C1C(=O)O
O=C(O)C1=CC=C(S)C=C1C(=O)O
O=CC1=CC=C(C(=O)O)C(=C1)C(=O)O
O=C(O)C=1C=C(C(=O)O)C(=CC1Br)C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)S(=O)(=O)N
O=C(O)C1=C(C(=O)O)C(=CC=C1N(=O)=O)N(=O)=O
O=C(O)C1=CC=C(C=C1C(=O)O)NC(=O)OC(C)(C)C
O=C(O)C=1C(Br)=CC=C(Br)C1C(=O)O
O=C(O)C=1C=C(C(=O)O)C(C(=O)O)=C(C1C(=O)O)C(F)(F)F
O=C(O)C=1C=C(C(=O)O)C(C(=O)O)=C(C1)C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)C(=O)OCC
O=C(O)C=1C=CC=C(OC2=CC=C(C=C2)C)C1C(=O)O
O=C(O)C=1C=CC=C(OCC2=CC=C(C=C2)CO)C1C(=O)O
O=C(O)C1=CC=C(C(NC(=O)C)=C1C(=O)O)N(=O)=O
O=C(O)C=1C=CC(=CC1C(=O)O)C=2C=CC=CC2
O=C(O)C1=CC(F)=C(Br)C=C1C(=O)O
O=C(O)C=1C=C(C(=O)O)C(=CC1Cl)C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)C(N)C(=O)O
O=C(O)C1=CC=C(Cl)C(=C1C(=O)O)N(=O)=O
O=C(O)C=1C=C(C=C(C1C(=O)O)N(=O)=O)N(=O)=O
O=C(O)C=1C=C(C(=O)O)C(=CC1O)C(=O)O
O=C(O)C1=CC(OC)=C(Cl)C(Cl)=C1C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)CC(NC(=O)OC(C)(C)C)C
O=C(O)C=1C=CC=2C=CC=CC2C1C(=O)O
O=C(O)C1=CC(OC)=CC(=C1C(=O)O)C
O=C(O)C1=CC=C(C#CC=2C=CC=CC2)C=C1C(=O)O
O=C(O)C1=CC=C(F)C(=C1C(=O)O)C(F)(F)F
O=C(O)C1=C(OCC)C=2C=CC=CC2C(OCC)=C1C(=O)O
O=C(O)C1=CC=C(C=C)C=C1C(=O)O
O=C(O)C=1C=C(C(=CC1C(=O)O)CC)CC
O=C(O)C1=CC=C(C=C1C(=O)O)C(N)C(=O)O
O=C(O)C=1C(Cl)=CC=C(C1C(=O)O)C(F)(F)F
O=C(O)C1=CC=C(O)C(O)=C1C(=O)O
O=C(O)C1=CC(O)=C(N)C=C1C(=O)O
O=C(O)C1=CC=C(C(OC)=C1C(=O)O)C
O=C(O)C=1C=CC=C(NO)C1C(=O)O
O=C(O)C1=CC=C(OC2=CC=C(C(=O)O)C(=C2)C(=O)O)C=C1
O=C(O)C1=CC(Cl)=C(C=C1C(=O)O)C(F)(F)F
O=C(O)C1=CC(N)=C(N)C=C1C(=O)O
O=C(O)C=1C=C(C(=CC1C(=O)O)C(C)C)C
O=C(O)C1=CC=C(C=C1C(=O)O)NN
O=C(O)C1=CC(N=NC=2C=C(C(=O)O)C(C(=O)O)=C(C2)C(=O)O)=CC(C(=O)O)=C1C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)C(NC(=O)OC(C=2C=CC=CC2N(=O)=O)C)C(=O)O
N#CC1=CC=C(C(=O)O)C(=C1)C(=O)O
O=NC1=CC=CC(C(=O)O)=C1C(=O)O
O=C(O)C=1C=CC=C(NCC=2C=NC=CC2)C1C(=O)O
O=C(O)C=1C(C(=O)O)=C(C(C(=O)O)=C(C(=O)O)C1C(F)(F)F)C(F)(F)F
O=C(O)C=1C=CC=C(NC(=O)OCC2C=3C=CC=CC3C=4C=CC=CC42)C1C(=O)O
O=C(O)C1=CC=C(C(N)=C1C(=O)O)C
O=C(O)C1=C(F)C(F)=C(O)C(F)=C1C(=O)O
O=C(O)C1=CC=C(OS(=O)(=O)C=2C=CC=CC2)C=C1C(=O)O
O=C(O)C1=C(O)C=C2C(=O)C3=C(O)C(O)=C(C(O)=C3C(=O)C2=C1C(=O)O)C4=CC(=CC=C4O)CCN
O=C(O)C1=CC(O)=CC(C(=O)O)=C1C(=O)O
O=C(O)C1=CC(Br)=CC(Cl)=C1C(=O)O
O=C(O)C1=CC=C(C=C1)C=2C=CC=C(C(=O)O)C2C(=O)O
O=C(O)C=1C=C(C(=O)O)C(=CC1C(=O)O)N(=O)=O
O=C(O)C1=CC=C(OC2=CC=C(C=C2)N(=O)=O)C=C1C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)S(=O)(=O)C2=CC=C(C(=O)O)C(=C2)C(=O)O
O=C(O)C=1C=CC=C(N=N(=O)C=2C=CC=C(C(=O)O)C2C(=O)O)C1C(=O)O
O=C(O)C=1C=C2C(=CC1C(=O)O)C3C=4C=CC=CC4C2C5=CC(C(=O)O)=C(C=C53)C(=O)O
O=C(O)C1=C(O)C=C2C(=O)C=3C(O)=C(C(C(=O)C)=C(O)C3C(=O)C2=C1C(=O)O)CC
O=C(O)C1=C(C(=O)O)C(=CC=C1C)C
O=C(O)C1=CC(O)=C(OC)C=C1C(=O)O
O=C(O)C1=CC=CC(C=2C=CC=CC2)=C1C(=O)O
O=C(O)C=1C=C(C(=O)O)C(=CC1N)C(=O)O
O=C(O)C1=CC=C(OC(C)C)C=C1C(=O)O
O=C(O)C1=CC=CC(C=2C=CC=CC2C)=C1C(=O)O
O=C(O)C1=CC=CC(=C1C(=O)O)S(=O)(=O)N
O=C(O)C1=CC=C(C=C1C(=O)O)NC(=O)C
O=C(O)C1=CC=C(OC2=CC=C(N)C=C2)C=C1C(=O)O
O=C(O)C=1C=CC=CC1C(=O)C2=CC=C(C(=O)O)C(=C2)C(=O)O
O=C(O)C=1C=CC=C(NCC=2SC=CC2)C1C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)C(=O)OCCOC(=O)C(=C)C
O=C(O)C=1C=CC=C(NCC=2OC(=CC2)C)C1C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)C(=O)C2=CC=C(C=C2)C(=O)C3=CC=C(C(=O)O)C(=C3)C(=O)O
O=C(O)C1=CC=C2C(=C1C(=O)O)C(C=3C=CC=CC3)(C)CC2(C)C
O=C(O)C=1C=CC=C(C=C)C1C(=O)O
N#CC=1C=C(C(=O)O)C(=CC1C#N)C(=O)O
O=C(O)C=1C=CC=C(NN)C1C(=O)O
O=C(O)C=1C=C2N=CC=CC2=CC1C(=O)O
O=C(O)C1=CC=C2N=CC=CC2=C1C(=O)O
O=C(O)C1=CC=C(OC2CC2)C=C1C(=O)O
O=C(O)C1=CC(N)=C(C=C1C(=O)O)N(=O)=O
O=C(O)C1=CC=2C=CNC2C=C1C(=O)O
O=C(O)C=1C=CC=C(NCC2CC2)C1C(=O)O
O=C(O)C1=CC=C(F)C(=C1C(=O)O)N(=O)=O
O=C(O)C1=CC=C(OC2=CC=CC(N)=C2)C=C1C(=O)O
O=C(O)C=1C=CC=C(OC2=CC=CC(C(=O)O)=C2C(=O)O)C1
O=C(O)C1=CC=C(OC2=CC=CC(C(=O)O)=C2C(=O)O)C=C1
O=C(O)C1=CC(F)=C(C=C1C(=O)O)C(F)(F)F
O=C(O)C=1C=C2C=C3C=C(C(=O)O)C(=CC3=CC2=CC1C(=O)O)C(=O)O
O=C(O)C1=CC=C(OC2=CC=C(C=C2)C(C3=CC=C(OC4=CC=CC(C(=O)O)=C4C(=O)O)C=C3)(C)C)C=C1C(=O)O
O=C(O)C=1C=C(C=C(C1C(=O)O)C)C
O=C(O)C1=CC=C(OCC)C=C1C(=O)O
O=C(O)C1=CC(O)=C(C(=O)O)C(=C1)C(=O)O
O=C(O)C=1C(F)=CC=C(C1C(=O)O)C
O=C(O)C1=CC(F)=CC(=C1C(=O)O)C
O=C(O)C1=CC(O)=C(C(=O)O)C(=C1C(=O)O)C
O=C(O)C=1C=C(F)C=C(F)C1C(=O)O
O=C(O)C=1C=CC=C(NCC)C1C(=O)O
O=C(O)C=1C=C(OC)C=C(OC)C1C(=O)O
O=C(O)C=1C(OC)=CC=C(OC)C1C(=O)O
O=C(Cl)C1=CC=C(C(=O)O)C(=C1)C(=O)O
O=C(O)C=1C=CC(=CC1)C2=CC=C(C(=O)O)C(=C2)C(=O)O
O=C(O)C=1C=CC=C(C1)C=2C=CC(C(=O)O)=C(C2)C(=O)O
O=C(O)C=1C=CC=C(OC2CC2)C1C(=O)O
O=C(O)C1=CC=CC(=C1C(=O)O)C(F)(F)F
O=C(O)C1=CC=C(OCC=2C=CC=CC2)C=C1C(=O)O
O=C(O)C1=CC=C(C=CC=2C=CC=CC2)C=C1C(=O)O
O=C(O)C=1C=CC=C(C2=CC=CC=3C=CC=CC32)C1C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)C=2C=CC=C(C(=O)O)C2C(=O)O
O=C(O)C1=CC=CC(C(=O)C=2C=CC=CC2)=C1C(=O)O
O=C(O)C=1C(Cl)=C(C(=O)O)C(C(=O)O)=C(Cl)C1C(=O)O
O=C(O)C1=CC=C2C(=C1C(=O)O)C(N)CC2
O=C(O)C1=CC=CC(=C1C(=O)O)N2C=NN=C2
O=C(O)C1=CC=C(C=C1C(=O)O)N2C=NN=C2
O=C(O)C1=CC=2C=CN(C2C=C1C(=O)O)C
O=C(O)C1=CC=2N=C(SC2C=C1C(=O)O)C
O=C(O)C1=CC(=CC(=C1)C(=O)O)NC(=O)C2=CC=C(C(=O)O)C(=C2)C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)N2C(=CC=C2C)C
O=C(O)C=1C=CC=C(NC(=O)OCC=2C=CC=CC2)C1C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)C(=O)C2=CC=CC(=C2)C(=O)C3=CC=C(C(=O)O)C(=C3)C(=O)O
O=C(O)C1=CC=C2C(=O)C=3C=CC=CC3C(=O)C2=C1C(=O)O
O=C(O)C1=CC=C(OC=2C=CC(=C3C=CC=NC23)S(=O)(=O)O)C=C1C(=O)O
O=C(O)C1=CC=C(C(=C1C(=O)O)C)C
O=C(O)C1=CC=CC(=C1C(=O)O)CC
O=C(O)C=1C(O)=CC=C(C1C(=O)O)C
O=CC1=CC=CC(C(=O)O)=C1C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)CN
O=C(O)C=1C=C(C(=O)O)C(=CC1C(=O)O)C
O=C(O)C1=CC=C(SC)C=C1C(=O)O
O=C(O)C1=CC=C(O)C(N)=C1C(=O)O
O=C(O)C1=CC(Br)=C(C=C1C(=O)O)C
O=C(O)C1=CC=C(C(Cl)=C1C(=O)O)C
O=C(O)C1=CC(Cl)=CC(=C1C(=O)O)C
O=C(O)C1=CC(=CC(OC)=C1C(=O)O)C
O=C(O)C1=CC=C(C=C1C(=O)O)CC(N)C
O=C(O)C1=CC(Cl)=C(O)C=C1C(=O)O
O=C(O)C=1C(O)=CC=C(OC)C1C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)N(C)C
O=C(O)C1=CC(Cl)=CC(F)=C1C(=O)O
O=C(O)C1=CC=2C=CC=C(O)C2C=C1C(=O)O
O=C(O)C=1C=CC=C(OCCC)C1C(=O)O
O=C(O)C1=CC=C(OC)C(N)=C1C(=O)O
O=C(O)C1=CC=2C=NN=CC2C=C1C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)CC(=O)C
O=C(O)C1=CC(Br)=C(OC)C=C1C(=O)O
O=C(O)C1=CC=C(OC)C(F)=C1C(=O)O
O=CC=1C(O)=C(O)C=C(C(=O)O)C1C(=O)O
O=C(O)C=1C(F)=CC(F)=C(F)C1C(=O)O
O=C(O)C=1C(Cl)=CC=C(OC)C1C(=O)O
O=C(O)C1=CC(OC)=C(O)C(OC)=C1C(=O)O
O=C(O)C1=CC(Cl)=C(O)C(Cl)=C1C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)C(=O)OC
O=C(O)C=1C(O)=C(C(=O)O)C(C(=O)O)=C(O)C1C(=O)O
O=C(O)C=1C=CC(=CC1C(=O)O)C=2C=CN=CC2
O=C(O)C1=CC=2C=C(C(=O)O)C(=CC2C=C1C(=O)O)C(=O)O
O=C(O)C=1C=CC=C(OCC=2C=CC=CC2)C1C(=O)O
O=C(O)C=1C=C2C=C(F)C(F)=CC2=CC1C(=O)O
O=C(O)C=1C=C(C(=O)O)C(C(=O)O)=C(C1)N(=O)=O
O=C(O)C1=CC=2N=NNC2C=C1C(=O)O
O=C(O)C1=CC=CC(=C1C(=O)O)N2CCCC2
O=C(O)C=1C(F)=C(C(=O)O)C(C(=O)O)=C(F)C1C(=O)O
O=C(O)C=1C=C2C=CC=C(C2=CC1C(=O)O)N(=O)=O
O=C(O)C=1C(Cl)=CC=C(C1C(=O)O)N(=O)=O
O=C(O)C1=CC=C(C=C1C(=O)O)C(=O)C2=CC=C(N)C=C2
O=C(O)C1=CC=C2C(=C1C(=O)O)CCC2N
O=C(O)C1=C(C(=O)O)C(C=2C=CC=CC2)=C(C=3C=CC=CC3)C(C=4C=CC=CC4)=C1C=5C=CC=CC5
O=C(O)C1=CC=C(OC2=CC=C(C=C2)C(=O)C=3C=CC=CC3)C=C1C(=O)O
O=C(O)C=1C=C(C(=O)O)C(=CC1C(=O)O)C(=O)C2=CC(C(=O)O)=C(C=C2C(=O)O)C(=O)O
O=C(O)C=1C(F)=C(F)C(=C(F)C1C(=O)O)C2=C(F)C(F)=C(C(=O)O)C(C(=O)O)=C2F
O=C(O)C1=CC=C(OC2=CC=C(C=C2)NC(=O)C=3SC=CC3)C=C1C(=O)O
O=C(O)C=1C=C2C(=CC1C(=O)O)C(NC(=O)OC(C)(C)C)CC2
O=C(O)C=1C=C2C(=CC1C(=O)O)C(NC(=O)OCC=3C=CC=CC3)CC2
O=C(O)C1=CC(O)=CC(=C1C(=O)O)C
O=C(O)C1=CC=C(C=C1C(=O)O)CC
O=C(O)C=1C=C(O)C=C(O)C1C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)C(C)C
O=C(O)C=1C=CC=C(SC)C1C(=O)O
O=C(O)C=1C=CC=C(OCC)C1C(=O)O
O=C(O)C=1C(N)=CC=C(N)C1C(=O)O
O=C(O)C=1C=C(N)C=C(N)C1C(=O)O
O=C(O)C1=CC(Cl)=C(C=C1C(=O)O)C
O=C(O)C1=CC(OC)=CC(O)=C1C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)CCCC
O=C(O)C1=CC(OC)=C(C=C1C(=O)O)C
O=C(O)C1=CC=C(OC)C(=C1C(=O)O)C
O=C(O)C1=CC(=CC(F)=C1C(=O)O)C
O=C(O)C1=CC(F)=C(C=C1C(=O)O)C
O=C(O)C=1C=CC=C(SCC)C1C(=O)O
O=C(O)C1=CC=C(OC)C(O)=C1C(=O)O
O=C(O)C1=CC=C(SCC)C=C1C(=O)O
O=C(O)C1=CC=C(O)C(Cl)=C1C(=O)O
O=C(O)C1=CC(F)=C(O)C=C1C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)C(=O)C
O=C(O)C=1C=C(Br)C=C(Br)C1C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)CCC(=O)O
O=C(O)C=1C=CC2=CC=CN=C2C1C(=O)O
O=CCCC=1C=CC=C(C(=O)O)C1C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)C(N)CN
O=C(O)C=1C=C(C(=O)O)C(=CC1OC)C(=O)O
O=C(O)C1=CC=C(N=C=S)C=C1C(=O)O
O=C(O)C1=CC=C(OC)C(Cl)=C1C(=O)O
O=C(O)C1=CC(Cl)=C(OC)C=C1C(=O)O
O=C(O)C=1C=CC=C(OCC=C)C1C(=O)O
O=C(O)C=1C=CC=C(OC(C)(C)C)C1C(=O)O
O=C(O)C1=CC=C2OCOC2=C1C(=O)O
O=C(O)C=1C=2C=CC=CC2C=3C=CC=CC3C1C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)C=2C=CC(N)=CC2
O=C(O)C=1C=C(C(=O)O)C(C(=O)O)=C(Br)C1C(=O)O
O=C(O)C1=CC=2SC=CC2C=C1C(=O)O
O=C(O)C1=CC=2OCCOC2C=C1C(=O)O
O=C(O)C=1C(O)=CC=C(C=2C=CC(=CC2)C)C1C(=O)O
O=C(O)C1=CC(=CC(Br)=C1C(=O)O)C(C)(C)C
O=C(O)C1=CC(O)=C(C=C1C(=O)O)N(=O)=O
O=C(O)C1=CC=C(C=C1C(=O)O)NC(=S)N
O=C(O)C=1C=CC=2C(=CC=C(C(=O)O)C2C(=O)O)C1C(=O)O
O=C(O)C=1C=C2C(=CC1C(=O)O)CC(O)C2
O=C(O)C1=CC=C2OCOCC2=C1C(=O)O
O=C(O)C1=CC=CC(=C1C(=O)O)C(Cl)C(=O)C
O=C(O)C1=CC=CC(=C1C(=O)O)CC(=O)CBr
O=C(O)C1=CC=2C=CC=CC2C(C=3C=CC=CC3)=C1C(=O)O
O=C(O)C1=CC=C(OC=2C=NC=CC2)C=C1C(=O)O
O=C(O)C=1C(O)=CC=C(OC=2C=CC=CC2)C1C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)C(=O)C(Br)C
O=C(O)C1=C(F)C(F)=C(OC)C(F)=C1C(=O)O
O=C(O)C=1C(F)=CC=C(C1C(=O)O)N(=O)=O
O=C(O)C=1C=CC=C(OC=2C=NC=CC2)C1C(=O)O
O=C(O)C1=CC(Cl)=C(C=C1C(=O)O)N(=O)=O
O=C(O)C1=CC=C(C=C1C(=O)O)C(=O)CCBr
O=C(O)C1=CC=CC(C(=O)C(Br)C)=C1C(=O)O
O=C(O)C1=CC=CC(C(=O)CCBr)=C1C(=O)O
O=C(O)C=1C=C2C=CC=C(C2=CC1C(=O)O)S(=O)(=O)O
O=C(O)C=1C=C2C(=CC1C(=O)O)C(N)CC2
O=C(O)C=1C=CC(=CC1C(=O)O)C2=CC=C(C=C2)N(=O)=O
O=C(O)C1=CC(Cl)=C(Cl)C(=C1C(=O)O)N(=O)=O
O=C(O)C=1C=CC=C(OC2=CC=CC(C(=O)O)=C2C(=O)O)C1C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)C(=O)OCC(CC)CCCC
O=C(O)C1=CC=C2C(C(=O)CC2)=C1C(=O)O
O=C(O)C1=CC(=CC(C(=O)O)=C1C(=O)O)C=2C=C(C(=O)O)C(C(=O)O)=C(C2)C(=O)O
O=C(O)C=1C=CC(=CC1C(=O)O)C=2C=CC(=CC2)C3=CC=C(C(=O)O)C(=C3)C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)C(=O)C2=CC=C(Cl)C=C2
O=C(O)C1=CC=C2C(C(=O)CCC2)=C1C(=O)O
O=C(O)C1=CC=C2C(=O)C=CC2=C1C(=O)O
O=C(O)C=1C=NC=C(OC2=CC=CC(C(=O)O)=C2C(=O)O)C1
O=C(O)C=1C=C(C(=CC1C(=O)O)C(F)(F)F)C(F)(F)F
O=C(O)C1=CC=C(C=C1C(=O)O)C2CCC(C(=O)O)C(C(=O)O)C2
O=C(OCCOC(=O)C1=CC=C(C(=O)O)C(=C1)C(=O)O)C=C
O=C(O)C=1C=CC(=CC1)C2=C(C(=O)O)C(C(=O)O)=C(C3=CC=C(C=C3)C(=O)O)C(C(=O)O)=C2C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)S(=O)(=O)OC=2C=CC=CC2
N#CC1=CC=C(C=C1)C(=O)NC2=CC=C(C(=O)O)C(=C2)C(=O)O
O=C(O)C1=CC=C(C=C1)NC(=O)C2=CC=C(C(=O)O)C(=C2)C(=O)O
O=C(O)C1=CC(OC2=CC=C(OC)C=C2)=C(OC3=CC=C(OC)C=C3)C=C1C(=O)O
O=C(O)C=1C=CC=C(N=NC2=CC=CC(C(=O)O)=C2C(=O)O)C1C(=O)O
O=C(O)C=1C=C(C=C(C1)C=2C(C(=O)O)=C(C(=O)O)C(C=3C=C(C=C(C3)C(=O)O)C(=O)O)=C(C(=O)O)C2C(=O)O)C(=O)O
O=C(O)C1=CC=C2C(=O)C(Cl)CC2=C1C(=O)O
O=C(O)C1=CC=C(OC2=CC=C(OC3=CC=C(C(=O)O)C(=C3)C(=O)O)C=C2)C=C1C(=O)O
O=C(O)C1=CC=C(N=NC2=CC=C(C(=O)O)C(=C2)C(=O)O)C=C1C(=O)O
O=C(O)C1=CC(O)=C(C=C1C(=O)O)NC(=O)OC(C)(C)C
O=C(O)C1=CC=C2C(=C1C(=O)O)C3C=CC4C=CC2C43
O=C(O)C1=CC=C(C=C1C(=O)O)NC(=O)OCC=2C=CC=CC2
O=C(O)C1=CC=C2C(=O)C3=CC(C(=O)O)=C(C=C3C(=O)C2=C1)C(=O)O
O=C(O)C1=CC=C(OC2=CC=C(C=C2)C(=O)C3=CC=C(C(=O)O)C(=C3)C(=O)O)C=C1C(=O)O
O=C(O)C1=CC=C(OC2=CC=C(C=C2)NC(=O)C(C)C)C=C1C(=O)O
O=C(O)C1=CC=C(OC2=CC=C(C=C2)NC(=O)C=3C=CC=CC3)C=C1C(=O)O
O=C(O)C1=CC=C(OC2=CC=CC(=C2)NC(=O)C3=CC=C(C=C3)C)C=C1C(=O)O
O=C(O)C=1C=CN=C(C1)C2=NC(=CC(=C2)C3=CC=C(C(=O)O)C(=C3)C(=O)O)C4=NC=CC(=C4)C(=O)O
O=C(O)C=1C=CC=C(OC2=CC=C(C=C2)C(C3=CC=C(OC4=CC=CC(C(=O)O)=C4C(=O)O)C=C3)(C)C)C1C(=O)O
O=C(O)C1=CC=C(OC2=CC=C(C=C2)NC(=O)C3=CC=C(C(=C3)C)C)C=C1C(=O)O
O=C(O)C1=CC=C(OC2=CC=CC(=C2)NC(=O)C=3C=CC(=CC3)C=4C=CC=CC4)C=C1C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)C(=O)C2=CC=C(C=C2)NC(=O)C(C=3C=CC=CC3)C=4C=CC=CC4
O=C(O)C1=CC=C(OC2=CC=CC(=C2)NC(=O)C=3SC=CC3)C=C1C(=O)O
O=C(O)C=1C=C2C(=O)OC3(C4=CC=C(O)C=C4OC5=CC(O)=CC=C53)C2=CC1C(=O)O
O=C(O)C1=C(O)C=C2C(=O)C3=C(O)C(O)=C(C(O)=C3C(=O)C2=C1C(=O)O)C4=CC(=CC=C4O)CC(N)C(=O)O
N#CC1=CC=CC(C(=O)O)=C1C(=O)O
O=C(O)C1=CC=CC(=C1C(=O)O)CCC
O=C(O)C1=CC=C(C(=C1C(=O)O)C)CC
O=C(O)C=1C(N)=CC=C(C1C(=O)O)C
O=C(O)C=1C(O)=C(C=C(C1C(=O)O)C)C
O=C(O)C1=CC=CC(C(=O)N)=C1C(=O)O
O=C(O)C=1C=CC=C(OO)C1C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)C(=O)S
O=C(O)C1=CC=C(O)C(C(=O)O)=C1C(=O)O
O=C(O)C1=CC(O)=C(O)C(O)=C1C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)C(=O)N
O=C(O)C=1C(O)=C(O)C=C(C1C(=O)O)C
O=C(O)C1=CC=C(C(=O)O)C(C(=O)O)=C1O
O=C(O)C1=CC=C(C=C1C(=O)O)C(N)C
O=C(O)C1=CC=CC(=C1C(=O)O)CCCC
O=C(O)C1=CC=C(C(=C1C(=O)O)C)CCCC
O=C(O)C1=CC=C(Cl)C(O)=C1C(=O)O
O=C(O)C1=CC(O)=CC(F)=C1C(=O)O
O=C(O)C=1C(Cl)=CC=C(O)C1C(=O)O
O=C(O)C=1C(F)=CC=C(O)C1C(=O)O
O=C(O)C=1C(O)=CC=C(C1C(=O)O)CCC
O=C(O)C1=CC=C(Br)C(Br)=C1C(=O)O
O=C(O)C1=CC(O)=C(C(=O)O)C(O)=C1C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)NO
O=C(O)C=1C=C(C(=O)O)C(C(=O)O)=C(C1C(=O)O)C
O=C(O)C=1C=CC=C(OCCO)C1C(=O)O
O=C(O)C=1C=CC=2C=NN=CC2C1C(=O)O
N#CCCC=1C=CC=C(C(=O)O)C1C(=O)O
O=CCCC1=CC=C(C(=O)O)C(=C1)C(=O)O
O=C(O)C1=CC=CC(C(=O)C)=C1C(=O)O
O=C(O)C1=CC(Br)=CC(C(=O)O)=C1C(=O)O
O=C(O)C=1C=C(C(=O)O)C(C(=O)O)=C(C(=O)O)C1O
O=C(O)C=1C=C(C(=O)O)C(C(=O)O)=C(O)C1C(=O)O
O=C(O)C=1C=CC2=CC=CC(=C2C1C(=O)O)C
O=C(O)C1=CC=CC(=C1C(=O)O)CC(=O)C
O=C(O)C1=CC(OC)=C(C(=O)O)C(=C1)C(=O)O
O=C(O)C1=CC=C(OC)C(C(=O)O)=C1C(=O)O
O=C(O)C1=CC=C(C(=O)O)C(C(=O)O)=C1OC
O=C(O)C1=CC=C(C=C1C(=O)O)C(=O)CC
O=C(O)C1=CC(OC)=C(OCC)C=C1C(=O)O
O=C(O)C=1C=CC=C(OCCCC)C1C(=O)O
O=C(O)C1=CC=2C=CC=C(N)C2C=C1C(=O)O
O=C(O)C=1C=CC=C(OCCCO)C1C(=O)O
O=C(O)C1=CC=C2N=CC=NC2=C1C(=O)O
O=C(O)C1=C(O)C=C(C(OC)=C1C(=O)O)C
O=C(O)C1=CC=CC(=C1C(=O)O)CCCBr
O=C(O)C1=CC=CC(C(=O)CC)=C1C(=O)O
O=C(O)C1=CC=CC(=C1C(=O)O)CCCCl
O=C(O)C1=CC(OC)=C(C(OC)=C1C(=O)O)C
O=C(O)C1=CC=C(OC)C(OCC)=C1C(=O)O
O=C(O)C1=CC=C2C(=C1C(=O)O)CCC2
O=C(O)C=1C(Br)=CC=C(OC)C1C(=O)O
O=C(O)C=1C=CC2=CC(=CN=C2C1C(=O)O)C
O=C(O)C=1C(F)=CC=C(OC)C1C(=O)O
O=C(O)C=1C=C2C(=CC1C(=O)O)CCCC2
O=C(O)C1=CC=CC(C(=O)OC)=C1C(=O)O
O=C(O)C1=CC(Cl)=C(SC)C=C1C(=O)O
O=C(O)C=1C=CC=C(OC=2C=CC=CC2)C1C(=O)O
O=C(O)C1=CC=C2C=CC=3C=CC=CC3C2=C1C(=O)O
O=C(O)C1=CC(C(=O)O)=C(C=C1C(=O)O)C=2C=CC=CC2
O=C(O)C1=C(C(=O)O)C(=CC=C1N(=O)=O)C
O=C(O)C=1C=CC=C(SC=2C=CC=CC2)C1C(=O)O
O=C(O)C=1C=C(C(=O)O)C(C(=O)O)=C(C(=O)O)C1OC
O=C(O)C1=CC=C(C=C1C(=O)O)S(=O)(=O)Cl
O=C(O)C1=CC=C(C=C1C(=O)O)C(N)(C(=O)O)C
O=C(O)C=1C=CC=C(NCCCC)C1C(=O)O
O=C(O)C1=CC(OC)=C(OCC)C(OC)=C1C(=O)O
O=C(O)C=1C(N)=CC=C(C1C(=O)O)N(=O)=O
O=C(O)C=1C=CC=C(NCCOC)C1C(=O)O
O=C(O)C1=CC=C(N)C(=C1C(=O)O)N(=O)=O
O=C(O)C1=CC=C2OCCOC2=C1C(=O)O
O=C(O)C1=CC=C(C(=C1C(=O)O)CC=C(C)C)C
O=C(O)C1=CC(N)=CC(=C1C(=O)O)N(=O)=O
O=C(O)C1=CC=C(OC2=CC=C(OC)C=C2)C=C1C(=O)O
O=C(O)C=1C=CC=C(NC(=O)CO)C1C(=O)O
O=C(O)C1=C(F)C(F)=C(N)C(F)=C1C(=O)O
O=C(O)C1=CC(Cl)=C(SC)C(Cl)=C1C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)C(Br)C(=O)C
O=C(O)C1=CC=CC(=C1C(=O)O)C(Br)C(=O)C
O=C(O)C1=CC=C(C=C1C(=O)O)C(=O)OCCO
O=C(O)C1=CC=C2C(=C1C(=O)O)CNCC2
O=C(O)C1=CC(Cl)=C(Cl)C(SC)=C1C(=O)O
O=C(O)C1=CC=2ON=CC2C=C1C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)NCC=2C=CC=CC2
O=C(O)C1=CC=C(C(Br)=C1C(=O)O)N(=O)=O
O=C(O)C1=CC=C(C=C1C(=O)O)C(=O)OCCCC
O=C(O)C1=CC=C(OC=2C(=CC=CC2C)C)C=C1C(=O)O
O=C(O)C=1C=C2C=C3C=CC=C(N)C3=CC2=CC1C(=O)O
O=C(O)C1=C(OC)C=C(OC)C(=C1C(=O)O)CCCC
O=C(O)C1=CC=C(OC)C(=C1C(=O)O)N(=O)=O
O=C(O)C1=CC=C(C#CC=2C=CC=C(F)C2)C=C1C(=O)O
O=C(O)C1=CC=2C=NNC2C=C1C(=O)O
O=C(O)C1=CC=CC(=C1C(=O)O)N2CCCCC2
O=C(O)C=1C=2C=CC=CC2C=3C=4C=CC=CC4C=CC3C1C(=O)O
O=C(O)C=1C=C(C=C(C1)C=2C=C(C(=O)O)C(C(=O)O)=C(C2)C(=O)O)C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)C(=O)C2=CC=C(O)C=C2
O=C(O)C1=CC=C(C=C1C(=O)O)C(=O)C2=CC=C(C(=C2)C)C
O=C(O)C1=CC2=CC=CC3=C2C(=C1C(=O)O)CC3
O=C(O)C1=CC=C(C=C1C(=O)O)CCC(=O)CCCCCCCCC
O=C(O)C1=CC=C(OC=2C=CC=CC2N)C=C1C(=O)O
O=C(O)C1=CC=2N=COC2C=C1C(=O)O
O=C(O)C1=CC(Cl)=C(C=C1C(=O)O)P(=O)(O)O
O=C(O)C1=CC=C(OC2=CC=C(F)C=C2)C=C1C(=O)O
O=C(O)C1=CC=C(OCC2=CC=C(C=C)C=C2)C=C1C(=O)O
O=C(O)C1=CC(F)=CC(=C1C(=O)O)C(F)(F)F
O=C(O)C=1C=C(C(=O)OC)C(=CC1C(=O)O)C(=O)OC
O=C(O)C1=CC=C(C=C1C(=O)O)C(=O)C=2C=CC=C(N)C2
O=C(O)C1=CC(OC(C)C)=CC(=C1C(=O)O)N(=O)=O
O=C(O)C1=CC(N)=C(C=C1C(=O)O)C(=O)OCC
O=C(O)C1=CC=C(C=C1)C(=O)C2=CC=C(C(=O)O)C(=C2)C(=O)O
O=C(O)C1=CC=CC(=C1C(=O)O)N(CC=C)CC=C
O=C(O)C1=CC=C(C=C1C(=O)O)C(=O)C2=CC(=CC=C2C)C
O=C(O)C1=CC=C(C=C1C(=O)O)C=2C=CC=CC2N(=O)=O
O=C(O)C=1C=CC=C(OC2=CC=C(Cl)C=C2)C1C(=O)O
O=C(O)C1=CC=C2C(=C1C(=O)O)C(N)CC2
O=C(O)C1=CC=C2C(=C1C(=O)O)C(N)CC2
O=C(O)C1=CC=C(C=C1C(=O)O)NC(=O)C=2C=CC=CC2
O=C(O)C=1C(OC)=C(OC)C=C(C1C(=O)O)N(=O)=O
O=C(O)C1=CC=CC(=C1C(=O)O)N2CCC(O)CC2
O=C(O)C1=CC(F)=C2OCOC2=C1C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)[Si](C2=CC=C(C(=O)O)C(=C2)C(=O)O)(C)C
O=C(O)C1=CC(OCC=C(C)C)=C(C(OC)=C1C(=O)O)C
O=C(O)C1=CC=C(C=C1C(=O)O)NCC=2C=CC=C(Cl)C2
O=C(O)C=1C=C(C(=O)O)C(=CC1C(=O)O)C(=O)C2=CC=C(C=C2)C
O=C(O)C1=CC=C(C=C1C(=O)O)C(=O)OCCCCCCCCCCCCCCCCCC
O=C(O)C=1C=CC=2C=CC(=O)C2C1C(=O)O
O=C(O)C1=CC(NC(=O)C)=C(C=C1C(=O)O)N(=O)=O
O=C(O)C1=CC=C(C=C1C(=O)O)C=2C=CC(=CC2)C=3C=CC(=CC3)C=4C=CC(C(=O)O)=C(C4)C(=O)O
O=C(O)C=1C=C(C(=O)O)C(=CC1C(=O)O)C(=O)C2=CC=C(C(=C2)C)C
O=C(O)C1=CC=C(OCOC2=CC=C(C(=O)O)C(=C2)C(=O)O)C=C1C(=O)O
O=C(O)C1=CC=C(C#CC#CC2=CC=C(C(=O)O)C(=C2)C(=O)O)C=C1C(=O)O
O=C(O)C=1C=C2C(=O)OC(=O)C2=CC1C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)NCC=2OC=CC2
O=C(O)C1=C(OC)C(OC)=C(OC)C(=C1C(=O)O)N(=O)=O
O=C(O)C1=CC=2N=C(OC2C=C1C(=O)O)C
O=C(O)C=1C=C2C(=CC1C(=O)O)C(C)(C)CCC2(C)C
O=C(O)C1=CC=C(OC2=CC=C(OC3=CC=C(C(=O)O)C(=C3)C(=O)O)C=C2)C=C1
O=C(O)C=1C=C(C(=O)O)C(=CC1C(=O)O)C(=O)C=2C=C(C=C(C2C)C)C
O=C(O)C1=CC=CC(C2=CC=C3OCCOC3=C2)=C1C(=O)O
O=C(O)C=1C=C(C=C(C1)C=2C=C(C(=O)O)C(=CC2C=3C=C(C=C(C3)C(=O)O)C(=O)O)C(=O)O)C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)C(=O)C2=CC=C(C=C2)N(=O)=O
O=C(O)C=1C=C(C(=O)OCC)C(=CC1C(=O)O)N(=O)=O
N#CC1=CC=C(C=C1)C(=O)NC2=CC=CC(C(=O)O)=C2C(=O)O
O=C(O)C1=CC=C(C=C1)S(=O)(=O)C2=CC=C(C(=O)O)C(=C2)C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)S(=O)(=O)OC2=CC=CC(=C2)C
O=C(O)C1=CC(=CC(SC=2C=CC=CC2)=C1C(=O)O)N(=O)=O
O=C(O)C1=CC(OC=2C=CC=CC2OC)=C(OC=3C=CC=CC3OC)C=C1C(=O)O
O=C(O)C1=CC=2N=CN(C2C=C1C(=O)O)C
O=C(O)C=1C=C(C(=O)O)C(=CC1C(=O)O)C(=O)C2=CC=C(OC)C=C2
O=C(O)C1=CC=C(OC2=CC=C(C=C2)NC(=O)C)C=C1C(=O)O
O=C(O)C=1C=C2C(=CC1C(=O)O)C3C=4C=CC=CC4C2CC3
O=C(O)C1=CC=C(OC(OC2=CC=C(C(=O)O)C(=C2)C(=O)O)(C)C)C=C1C(=O)O
O=C(O)C1=CC=C2C(C(=O)CCC2(C)C)=C1C(=O)O
O=C(O)C1=CC=C(C=C1C(=O)O)S(=O)(=O)NC=2C=CC=CC2
O=C(O)C1=CC=C(N=NC2=CC=C(C=C2)N(CC)CC)C=C1C(=O)O

In [22]:
import pandas as pd

df1 = pd.read_csv(r"C:\Users\kkyom\OneDrive\デスクトップ\pka_activity\ver_4\out\csvfile\known\2nd_20260205.csv")
# 24行目を選択
df1 = df1.iloc[24:25]
df2 = pd.read_csv(r"C:\Users\kkyom\OneDrive\デスクトップ\pka_activity\ver_4\out\csvfile\unknown\unknown_data.csv")
df = pd.concat([df2, df1], ignore_index=True)
df.drop(columns=["yield"], inplace=True)
df.to_csv(r"C:\Users\kkyom\OneDrive\デスクトップ\pka_activity\ver_4\out\csvfile\unknown\unknown_data.csv", index=False)

In [1]:
θ = 0.5
print(θ)

0.5

In [4]:
base = ["C", "C", "C", "C"]
cn = "C#N"
no2 = "N(=O)=O"
base[0] = base[0] + "(" + cn + ")"
base[1] = base[1] + "(" + no2 + ")"
substruct = "OC(=O)C1=" + base[0] + base[1] + "=" + base[2] + base[3] + "=C1C(=O)O"
print(substruct)

OC(=O)C1=C(C#N)C(N(=O)=O)=CC=C1C(=O)O

In [25]:
functional_groups = {
    2: ("C#N", 0),
    "no2": ("N(=O)=O", 0),
    "f": ("F", 0),
    "cl": ("Cl", 0),
}

for i in functional_groups.keys():
    print(i)

2
no2
f
cl

In [22]:
functional_groups = {
    "cn": ("C#N", 0),
    "no2": ("N(=O)=O", 0),
    "f": ("F", 0),
    "cl": ("Cl", 0),
    "br": ("Br", 0),
    "h": ("", 0),
    "c6h5": ("C2=CC=CC=C2", 0),
    "ch3": ("C", 1),
    "oh": ("O", 1),
    "cho": ("C(=O)", 1),
    "cooh": ("C(=O)O", 1),
}

base = {
    "3": ["C", 1],
    "4": ["C", 1],
    "5": ["C", 1],
    "6": ["C", 1],
}

for c3 in functional_groups.items():
    base["3"][0] = "C"
    if c3[0] == "h":
        pass
    else:
        base["3"][0] += "(" + c3[1][0] + ")"
        base["3"][1] = c3[1][1]
    for c4 in functional_groups.items():
        base["4"][0] = "C"
        if c4[0] == "h":
            pass
        else:
            base["4"][0] += "(" + c4[1][0] + ")"
            base["4"][1] = c4[1][1]
        for c5 in functional_groups.items():
            base["5"][0] = "C"
            if c5[0] == "h":
                pass
            else:
                base["5"][0] += "(" + c5[1][0] + ")"
                base["5"][1] = c5[1][1]
            for c6 in functional_groups.items():
                base["6"][0] = "C"
                if c6[0] == "h":
                    pass
                else:
                    base["6"][0] += "(" + c6[1][0] + ")"
                    base["6"][1] = c6[1][1]
                print("OC(=O)C1=" + base["3"][0] + base["4"][0] + "=" + base["5"][0] + base["6"][0] + "=C1C(=O)O")

OC(=O)C1=C(C#N)C(C#N)=C(C#N)C(C#N)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C#N)C(N(=O)=O)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C#N)C(F)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C#N)C(Cl)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C#N)C(Br)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C#N)C=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C#N)C(C2=CC=CC=C2)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C#N)C(C)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C#N)C(O)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C#N)C(C(=O))=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C#N)C(C(=O)O)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(N(=O)=O)C(C#N)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(N(=O)=O)C(N(=O)=O)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(N(=O)=O)C(F)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(N(=O)=O)C(Cl)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(N(=O)=O)C(Br)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(N(=O)=O)C=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(N(=O)=O)C(C2=CC=CC=C2)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(N(=O)=O)C(C)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(N(=O)=O)C(O)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(N(=O)=O)C(C(=O))=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(N(=O)=O)C(C(=O)O)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(F)C(C#N)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(F)C(N(=O)=O)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(F)C(F)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(F)C(Cl)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(F)C(Br)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(F)C=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(F)C(C2=CC=CC=C2)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(F)C(C)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(F)C(O)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(F)C(C(=O))=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(F)C(C(=O)O)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(Cl)C(C#N)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(Cl)C(N(=O)=O)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(Cl)C(F)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(Cl)C(Cl)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(Cl)C(Br)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(Cl)C=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(Cl)C(C2=CC=CC=C2)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(Cl)C(C)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(Cl)C(O)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(Cl)C(C(=O))=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(Cl)C(C(=O)O)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(Br)C(C#N)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(Br)C(N(=O)=O)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(Br)C(F)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(Br)C(Cl)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(Br)C(Br)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(Br)C=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(Br)C(C2=CC=CC=C2)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(Br)C(C)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(Br)C(O)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(Br)C(C(=O))=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(Br)C(C(=O)O)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=CC(C#N)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=CC(N(=O)=O)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=CC(F)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=CC(Cl)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=CC(Br)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=CC=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=CC(C2=CC=CC=C2)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=CC(C)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=CC(O)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=CC(C(=O))=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=CC(C(=O)O)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C2=CC=CC=C2)C(C#N)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C2=CC=CC=C2)C(N(=O)=O)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C2=CC=CC=C2)C(F)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C2=CC=CC=C2)C(Cl)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C2=CC=CC=C2)C(Br)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C2=CC=CC=C2)C=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C2=CC=CC=C2)C(C2=CC=CC=C2)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C2=CC=CC=C2)C(C)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C2=CC=CC=C2)C(O)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C2=CC=CC=C2)C(C(=O))=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C2=CC=CC=C2)C(C(=O)O)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C)C(C#N)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C)C(N(=O)=O)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C)C(F)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C)C(Cl)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C)C(Br)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C)C=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C)C(C2=CC=CC=C2)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C)C(C)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C)C(O)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C)C(C(=O))=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C)C(C(=O)O)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(O)C(C#N)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(O)C(N(=O)=O)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(O)C(F)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(O)C(Cl)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(O)C(Br)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(O)C=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(O)C(C2=CC=CC=C2)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(O)C(C)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(O)C(O)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(O)C(C(=O))=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(O)C(C(=O)O)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C(=O))C(C#N)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C(=O))C(N(=O)=O)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C(=O))C(F)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C(=O))C(Cl)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C(=O))C(Br)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C(=O))C=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C(=O))C(C2=CC=CC=C2)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C(=O))C(C)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C(=O))C(O)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C(=O))C(C(=O))=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C(=O))C(C(=O)O)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C(=O)O)C(C#N)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C(=O)O)C(N(=O)=O)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C(=O)O)C(F)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C(=O)O)C(Cl)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C(=O)O)C(Br)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C(=O)O)C=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C(=O)O)C(C2=CC=CC=C2)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C(=O)O)C(C)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C(=O)O)C(O)=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C(=O)O)C(C(=O))=C1C(=O)O
OC(=O)C1=C(C#N)C(C#N)=C(C(=O)O)C(C(=O)O)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C#N)C(C#N)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C#N)C(N(=O)=O)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C#N)C(F)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C#N)C(Cl)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C#N)C(Br)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C#N)C=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C#N)C(C2=CC=CC=C2)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C#N)C(C)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C#N)C(O)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C#N)C(C(=O))=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C#N)C(C(=O)O)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(N(=O)=O)C(C#N)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(N(=O)=O)C(N(=O)=O)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(N(=O)=O)C(F)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(N(=O)=O)C(Cl)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(N(=O)=O)C(Br)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(N(=O)=O)C=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(N(=O)=O)C(C2=CC=CC=C2)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(N(=O)=O)C(C)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(N(=O)=O)C(O)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(N(=O)=O)C(C(=O))=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(N(=O)=O)C(C(=O)O)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(F)C(C#N)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(F)C(N(=O)=O)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(F)C(F)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(F)C(Cl)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(F)C(Br)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(F)C=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(F)C(C2=CC=CC=C2)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(F)C(C)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(F)C(O)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(F)C(C(=O))=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(F)C(C(=O)O)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(Cl)C(C#N)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(Cl)C(N(=O)=O)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(Cl)C(F)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(Cl)C(Cl)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(Cl)C(Br)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(Cl)C=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(Cl)C(C2=CC=CC=C2)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(Cl)C(C)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(Cl)C(O)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(Cl)C(C(=O))=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(Cl)C(C(=O)O)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(Br)C(C#N)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(Br)C(N(=O)=O)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(Br)C(F)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(Br)C(Cl)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(Br)C(Br)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(Br)C=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(Br)C(C2=CC=CC=C2)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(Br)C(C)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(Br)C(O)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(Br)C(C(=O))=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(Br)C(C(=O)O)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=CC(C#N)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=CC(N(=O)=O)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=CC(F)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=CC(Cl)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=CC(Br)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=CC=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=CC(C2=CC=CC=C2)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=CC(C)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=CC(O)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=CC(C(=O))=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=CC(C(=O)O)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C2=CC=CC=C2)C(C#N)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C2=CC=CC=C2)C(N(=O)=O)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C2=CC=CC=C2)C(F)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C2=CC=CC=C2)C(Cl)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C2=CC=CC=C2)C(Br)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C2=CC=CC=C2)C=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C2=CC=CC=C2)C(C2=CC=CC=C2)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C2=CC=CC=C2)C(C)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C2=CC=CC=C2)C(O)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C2=CC=CC=C2)C(C(=O))=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C2=CC=CC=C2)C(C(=O)O)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C)C(C#N)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C)C(N(=O)=O)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C)C(F)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C)C(Cl)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C)C(Br)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C)C=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C)C(C2=CC=CC=C2)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C)C(C)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C)C(O)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C)C(C(=O))=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C)C(C(=O)O)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(O)C(C#N)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(O)C(N(=O)=O)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(O)C(F)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(O)C(Cl)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(O)C(Br)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(O)C=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(O)C(C2=CC=CC=C2)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(O)C(C)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(O)C(O)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(O)C(C(=O))=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(O)C(C(=O)O)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C(=O))C(C#N)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C(=O))C(N(=O)=O)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C(=O))C(F)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C(=O))C(Cl)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C(=O))C(Br)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C(=O))C=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C(=O))C(C2=CC=CC=C2)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C(=O))C(C)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C(=O))C(O)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C(=O))C(C(=O))=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C(=O))C(C(=O)O)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C(=O)O)C(C#N)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C(=O)O)C(N(=O)=O)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C(=O)O)C(F)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C(=O)O)C(Cl)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C(=O)O)C(Br)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C(=O)O)C=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C(=O)O)C(C2=CC=CC=C2)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C(=O)O)C(C)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C(=O)O)C(O)=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C(=O)O)C(C(=O))=C1C(=O)O
OC(=O)C1=C(C#N)C(N(=O)=O)=C(C(=O)O)C(C(=O)O)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C#N)C(C#N)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C#N)C(N(=O)=O)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C#N)C(F)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C#N)C(Cl)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C#N)C(Br)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C#N)C=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C#N)C(C2=CC=CC=C2)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C#N)C(C)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C#N)C(O)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C#N)C(C(=O))=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C#N)C(C(=O)O)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(N(=O)=O)C(C#N)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(N(=O)=O)C(N(=O)=O)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(N(=O)=O)C(F)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(N(=O)=O)C(Cl)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(N(=O)=O)C(Br)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(N(=O)=O)C=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(N(=O)=O)C(C2=CC=CC=C2)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(N(=O)=O)C(C)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(N(=O)=O)C(O)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(N(=O)=O)C(C(=O))=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(N(=O)=O)C(C(=O)O)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(F)C(C#N)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(F)C(N(=O)=O)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(F)C(F)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(F)C(Cl)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(F)C(Br)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(F)C=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(F)C(C2=CC=CC=C2)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(F)C(C)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(F)C(O)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(F)C(C(=O))=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(F)C(C(=O)O)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(Cl)C(C#N)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(Cl)C(N(=O)=O)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(Cl)C(F)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(Cl)C(Cl)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(Cl)C(Br)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(Cl)C=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(Cl)C(C2=CC=CC=C2)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(Cl)C(C)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(Cl)C(O)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(Cl)C(C(=O))=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(Cl)C(C(=O)O)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(Br)C(C#N)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(Br)C(N(=O)=O)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(Br)C(F)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(Br)C(Cl)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(Br)C(Br)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(Br)C=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(Br)C(C2=CC=CC=C2)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(Br)C(C)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(Br)C(O)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(Br)C(C(=O))=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(Br)C(C(=O)O)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=CC(C#N)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=CC(N(=O)=O)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=CC(F)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=CC(Cl)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=CC(Br)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=CC=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=CC(C2=CC=CC=C2)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=CC(C)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=CC(O)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=CC(C(=O))=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=CC(C(=O)O)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C2=CC=CC=C2)C(C#N)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C2=CC=CC=C2)C(N(=O)=O)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C2=CC=CC=C2)C(F)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C2=CC=CC=C2)C(Cl)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C2=CC=CC=C2)C(Br)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C2=CC=CC=C2)C=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C2=CC=CC=C2)C(C2=CC=CC=C2)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C2=CC=CC=C2)C(C)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C2=CC=CC=C2)C(O)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C2=CC=CC=C2)C(C(=O))=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C2=CC=CC=C2)C(C(=O)O)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C)C(C#N)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C)C(N(=O)=O)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C)C(F)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C)C(Cl)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C)C(Br)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C)C=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C)C(C2=CC=CC=C2)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C)C(C)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C)C(O)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C)C(C(=O))=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C)C(C(=O)O)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(O)C(C#N)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(O)C(N(=O)=O)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(O)C(F)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(O)C(Cl)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(O)C(Br)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(O)C=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(O)C(C2=CC=CC=C2)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(O)C(C)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(O)C(O)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(O)C(C(=O))=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(O)C(C(=O)O)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C(=O))C(C#N)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C(=O))C(N(=O)=O)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C(=O))C(F)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C(=O))C(Cl)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C(=O))C(Br)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C(=O))C=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C(=O))C(C2=CC=CC=C2)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C(=O))C(C)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C(=O))C(O)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C(=O))C(C(=O))=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C(=O))C(C(=O)O)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C(=O)O)C(C#N)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C(=O)O)C(N(=O)=O)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C(=O)O)C(F)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C(=O)O)C(Cl)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C(=O)O)C(Br)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C(=O)O)C=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C(=O)O)C(C2=CC=CC=C2)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C(=O)O)C(C)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C(=O)O)C(O)=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C(=O)O)C(C(=O))=C1C(=O)O
OC(=O)C1=C(C#N)C(F)=C(C(=O)O)C(C(=O)O)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(C#N)C(C#N)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(C#N)C(N(=O)=O)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(C#N)C(F)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(C#N)C(Cl)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(C#N)C(Br)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(C#N)C=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(C#N)C(C2=CC=CC=C2)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(C#N)C(C)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(C#N)C(O)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(C#N)C(C(=O))=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(C#N)C(C(=O)O)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(N(=O)=O)C(C#N)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(N(=O)=O)C(N(=O)=O)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(N(=O)=O)C(F)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(N(=O)=O)C(Cl)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(N(=O)=O)C(Br)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(N(=O)=O)C=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(N(=O)=O)C(C2=CC=CC=C2)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(N(=O)=O)C(C)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(N(=O)=O)C(O)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(N(=O)=O)C(C(=O))=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(N(=O)=O)C(C(=O)O)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(F)C(C#N)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(F)C(N(=O)=O)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(F)C(F)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(F)C(Cl)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(F)C(Br)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(F)C=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(F)C(C2=CC=CC=C2)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(F)C(C)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(F)C(O)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(F)C(C(=O))=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(F)C(C(=O)O)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(Cl)C(C#N)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(Cl)C(N(=O)=O)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(Cl)C(F)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(Cl)C(Cl)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(Cl)C(Br)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(Cl)C=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(Cl)C(C2=CC=CC=C2)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(Cl)C(C)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(Cl)C(O)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(Cl)C(C(=O))=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(Cl)C(C(=O)O)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(Br)C(C#N)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(Br)C(N(=O)=O)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(Br)C(F)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(Br)C(Cl)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(Br)C(Br)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(Br)C=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(Br)C(C2=CC=CC=C2)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(Br)C(C)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(Br)C(O)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(Br)C(C(=O))=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(Br)C(C(=O)O)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=CC(C#N)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=CC(N(=O)=O)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=CC(F)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=CC(Cl)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=CC(Br)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=CC=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=CC(C2=CC=CC=C2)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=CC(C)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=CC(O)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=CC(C(=O))=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=CC(C(=O)O)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(C2=CC=CC=C2)C(C#N)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(C2=CC=CC=C2)C(N(=O)=O)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(C2=CC=CC=C2)C(F)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(C2=CC=CC=C2)C(Cl)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(C2=CC=CC=C2)C(Br)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(C2=CC=CC=C2)C=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(C2=CC=CC=C2)C(C2=CC=CC=C2)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(C2=CC=CC=C2)C(C)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(C2=CC=CC=C2)C(O)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(C2=CC=CC=C2)C(C(=O))=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(C2=CC=CC=C2)C(C(=O)O)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(C)C(C#N)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(C)C(N(=O)=O)=C1C(=O)O
OC(=O)C1=C(C#N)C(Cl)=C(C)C(F)=C1C(=O)O

In [ ]:
import datetime

now = datetime.date
print(now)

TypeError: descriptor 'strftime' for 'datetime.date' objects doesn't apply to a 'str' object

In [4]:
print("a")
display("a")
print(type(12))
display(type(12))

a

'a'

<class 'int'>

int

In [1]:
import datetime as dt
current = dt.date(2026, 3, 16)
print(current)

2026-03-16

In [2]:
current.test = "test"

AttributeError: 'datetime.date' object has no attribute 'test'

In [10]:
from rdkit import Chem

mol1 = Chem.MolFromSmiles("OC(=O)C1=CC=CC=C1C(=O)O")
mol2 = Chem.MolFromSmiles("COC(=O)C1=CC=CC=C1C(=O)O")
phthalic_pattern = Chem.MolFromSmarts("c1ccc(C(=O)[OH])c(C(=O)[OH])c1")

matches_list1 = mol1.GetSubstructMatches(phthalic_pattern)
matches_list2 = mol2.GetSubstructMatches(phthalic_pattern)
print(matches_list1)
print(matches_list2)
if matches_list1:
    print("mol1 has phthalic acid structure")
if matches_list2:
    print("mol2 has phthalic acid structure")

((5, 6, 7, 8, 9, 10, 11, 3, 1, 2, 0, 4),)
()
mol1 has phthalic acid structure

In [3]:
test = {
    1:1,
    2:2,
    3:3,
    4:4,
    5:5,
}
print(test)

{1: 1, 2: 2, 3: 3, 4: 4, 5: 5}

In [5]:
import itertools
a = list("abcd")
for i in itertools.combinations(a, 2):
    print(i)

('a', 'b')
('a', 'c')
('a', 'd')
('b', 'c')
('b', 'd')
('c', 'd')

In [37]:
from datetime import datetime, date

t = date.today().strftime("%Y%m%d")
print(t)

20260322

In [38]:
a = ("a", "b", "c")
print("|".join(a))

a|b|c

In [2]:
a = {1,3,4}
print(type(a))

<class 'set'>

In [7]:
dict1 = {"a": 1, "b": 2, "c": 3}
dict2 = {"a": 2, "b": 3, "c": 4}

result = []
result.append(dict1)
result.append(dict2)
print(result)

[{'a': 1, 'b': 2, 'c': 3}, {'a': 2, 'b': 3, 'c': 4}]

In [8]:
import pandas as pd
df = pd.DataFrame(result)
print(df)

   a  b  c
0  1  2  3
1  2  3  4

In [9]:
dict1 = {"d": 1, "e": 2, "f": 3}
dict2 = {"d": 2, "e": 3, "f": 4}

result = []
result.append(dict1)
result.append(dict2)

In [10]:
df[list(result[0].keys())] = pd.DataFrame(result, index=df.index)
print(df)

   a  b  c  d  e  f
0  1  2  3  1  2  3
1  2  3  4  2  3  4

In [12]:
result[0].keys()

dict_keys(['d', 'e', 'f'])

In [4]:
from pathlib import Path

base = Path("C:\Users\kyoma\Desktop\laboratory\ml\predict_activity\ver_4")
print(base)

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (640137429.py, line 3)

In [1]:
import datetime
print(type(datetime.date.today().strftime("%Y%m%d")))

<class 'str'>